### ISSUE TITLE
Expose slack inviter job via API

### ISSUE THREAD

**Issue by rickr** [OperationCode/operationcode_backend#102]
# Feature
## Why is this feature being added?

In order to support operationcode/operationcode_frontend#304 we should expose the slack inviter job via API.

## What should your feature do?

Add a new endpoint that when called invites the user to slack. This should be a POST request named something like `users/invite_to_slack`. It should require authorization. It should take the `current_user` and pass the needed parameters to the current invite to slack job.

**Comment by sethbergman** [comment]
What are the parameters being passed to the API? The current implementation for my slack invite is just a nice landing page form where the user enters their email and get's an automatic invite to the channel. I can tweak the form to have the required inputs, or just go with the POST request. 
I was kind of thinking that after they sign up through the already working form component, then they are redirected to the invite page. Can you elaborate on exactly what process the user goes through and what data you need to collect?

**Comment by rickr** [comment]
No params needed. When a user makes a request their JWT is passed in and we authenticate the user giving us access to the `User` object. 

After login users will be redirected to discourse as per operationcode/operationcode_frontend#308. We'll put some effort in other areas (discourse topics, welcome mailer, links in the profile) to make users aware of slack.
