### ISSUE TITLE
Remove Dev Bootcamp from code_schools.yaml

### ISSUE THREAD

**Issue by kylemh** [OperationCode/operationcode_backend#107]
# Feature
## Why is this feature being added?
According to [this](http://www.huffingtonpost.com/entry/early-coding-school-dev-bootcamp-shuts-down-what_us_5967ae75e4b09e26b6d7662a), Dev Bootcamp has shut down.

## What should your feature do?
Remove Dev Bootcamp from the code_schools.yaml file so our API does not serve it up to be rendered as a potential code school for veterans to use.

**Comment by ianroberts131** [comment]
Happy to help out on this. Still trying to get everything set up locally - should be able to submit a PR later this week though.
