### ISSUE TITLE
If a user is a mentor add them to the mentors group in discourse

### ISSUE THREAD

**Issue by rickr** [OperationCode/operationcode_backend#117]
# Feature
## Why is this feature being added?

If a user signs up as a mentor we can automatically add them to the mentors list in discourse, giving them special permissions and a title.

## What should your feature do?
Modify the SSO payload to check if a user is a mentor.
If they are add `add_groups: mentors` to the payload.
Ref: https://meta.discourse.org/t/official-single-sign-on-for-discourse/13045

This is gonna be a hard one to test so as long as the payload looks correct we'll test once live. #YOLO

**Comment by ianroberts131** [comment]
I'll give this 1 a try if it's still available

**Comment by kylemh** [comment]
@ianroberts131 all yours!
