### ISSUE TITLE
Emails should be downcased before saving

### ISSUE THREAD

**Issue by rickr** [OperationCode/operationcode_backend#118]
# Feature
## Why is this feature being added?

Emails should be stored in all lowercase in the database.

## What should your feature do?
Add a `before_save` filter to downcase email addresses on the `User` model.

**Comment by sabrown84** [comment]
Hi I'd like to try this one out. Is there any additional information that you think I will need? I noticed that in the user model has two validations for emails should I look to add a validation for this lowercase feature as well?

**Comment by ianroberts131** [comment]
I've actually been trying to get this setup, but having some issues getting my tests to run. Looks like @sabrown84 is going to take this 1, but I'd love to help on other issues so would still like to resolve the problems I'm having with the tests.

When I run `rake test`, I get the following error:

```
rake test
rake aborted!
Bundler::GemNotFound: Could not find nokogiri-1.7.1 in any of the sources
```

When I `bundle install`, I then get the following:

```
Gem::InstallError: nokogiri requires Ruby version < 2.4, >= 2.1.0.
An error occurred while installing nokogiri (1.7.1), and Bundler cannot
continue.
Make sure that `gem install nokogiri -v '1.7.1'` succeeds before bundling.
```

Any ideas? Thanks for your help.

**Comment by sabrown84** [comment]
Ok @ianroberts131 I haven't started setting it up I was just starting to think it through before jumping in. I may run into the same error...

**Comment by hpjaj** [comment]
@ianroberts131 - You can run the tests through [Docker](https://www.docker.com/).  Try this:

1. Start Docker
2. run `make setup`
3. run `make test`

**Comment by ianroberts131** [comment]
Thanks @hpjaj, that got me going in the right direction. Unfortunately, the version of Make installed [here](http://gnuwin32.sourceforge.net/packages/make.htm), per the `CONTRIBUTING.MD` file, is one version before a bug I was facing got fixed. Here's the error message I was getting:

```
C:\Program: Interrupt/Exception caught (code = 0xc00000fd, addr = 0x4227d3)
```

Ultimately was able to get it working by running make via MinGW, like so:

```
mingw32-make.exe test
```

Anyway, this isn't really relevant since @sabrown84 is taking this issue, but figured I would report back in case she or anyone else faces the same issue.

**Comment by sabrown84** [comment]
Thank you @ianroberts131 and @hpjaj. I thought I would have a similar problem, but I didn't.

**Comment by hpjaj** [comment]
np.  Feel free to ping me if you need a hand with anything!  If you're on the OC Slack channel, my handle is @harry

**Comment by sethbergman** [comment]
What about tackling this from the frontend? I think it would be easy to accomplish.

**Comment by hpjaj** [comment]
@sethbergman - I can't hurt to have a layer of validation on the frontend, but IMO we should have backstopped data integrity insurance in the backend.

@sabrown84 - In case you're interested, here's a [similar implementation](https://github.com/OperationCode/operationcode_backend/blob/master/app/models/user.rb#L103-L105) in the backend.

**Comment by sabrown84** [comment]
@hpjaj thank you yes I did see that and I used that, I'm just having trouble with creating a test and getting it to pass that test. I'm really close though.

**Comment by kylemh** [comment]
@sethbergman I'll make a ticket. We should do both.

**Comment by DRBragg** [comment]
should remove issues once they are merged so it is easier to see what issues are currently open to be worked on

**Comment by kylemh** [comment]
@DRBragg indeed. We have placeholder text on all PRs that automatically close fixed issues, but sometimes we miss it, if people remove that text.
