### ISSUE TITLE
Create flash notification system

### ISSUE THREAD

**Issue by rickr** [OperationCode/operationcode_backend#120]
# Feature
## Why is this feature being added?

When a user takes an action like resetting their password we should have a system in place to consistently notify them the action was successful.

## What should your feature do?
Add a flash message notification system.

Please discuss possible options for moving forward in the ticket before starting work.

**Comment by rickr** [comment]
One possible solution, although it requires redux.
https://github.com/posabsolute/redux-flash-notification

**Comment by PSkaggs** [comment]
Are **all** of the front end requests accessed through the API?  If so this seems like a front end implementation.

**Comment by rickr** [comment]
You are correct - this got filed in the wrong repo. Moving it now.

**Comment by rickr** [comment]
This issue was moved to OperationCode/operationcode_frontend#425
