### ISSUE TITLE
Add Rithm School to code_schools.yml

### ISSUE THREAD

**Issue by rickr** [OperationCode/operationcode_backend#121]
# Feature
## Why is this feature being added?

name: Rithm School
  url: rithmschool.com?utm_source=OperationCode&utm_medium=logo&utm_campaign=root
  logo: [SEE ATTACHMENT]
  full_time: true
  hardware_included: false
  has_online: false
  online_only: false
  locations:
    - va_accepted: false
      address1: 3338 17th St.
      address2: #100
      city: San Francisco
      state: CA
      zip: 94110

**Comment by PSkaggs** [comment]
I can do this.
Is there any opposition to alphabetizing the code_schools.yml file too?

**Comment by dquach217** [comment]
@rickr Has this been taken? If not can I make a PR for this?
