### ISSUE TITLE
Create scholarship models

### ISSUE THREAD

**Issue by rickr** [OperationCode/operationcode_backend#122]
# Feature
## Why is this feature being added?

See operationcode/operationcode_frontend#357 for some more background.

## What should your feature do?
Add a new scholarship model.
It should follow the pattern of this form: https://airtable.com/shroOCkoOu7vOXuyN

Scholarships should have the following attributes:
name - string
description - text
location - string
terms - text
start_date - datetime
end_date - datetime

Scholarships should have many applications
Users should have many applications

Applications should have the following attributes:
name (delegated to user)
email (delegated to user)
reason - text
terms_accepted - boolean

Only verified members should be able to submit an application.

**Comment by jmayergit** [comment]
what do you mean by delegated to user?

**Comment by rickr** [comment]
This might help: https://apidock.com/rails/Module/delegate
