### ISSUE TITLE
Password reset email should say "Operation Code" somewhere in the subject/From

### ISSUE THREAD

**Issue by togakangaroo** [OperationCode/operationcode_backend#123]
Reset the password for your Operation Code portal. You get an email that doesn't actually mention "Operation Code" anywhere. It should at a minimum mention Operation Code in the Subject or From fields so that it doesn't look like spam in your inbox (for example the from can be `Operation Code <staff@operationcode.org>`)

**Comment by PSkaggs** [comment]
I can do this.

**Comment by rickr** [comment]
@PSkaggs - all yours!
