### ISSUE TITLE
SLACK_SUBDOMAIN not set

### ISSUE THREAD

**Issue by sethbergman** [OperationCode/operationcode_backend#128]
# Bug Report
## What is the current behavior?
When standing up the backend, redis reports that the `SLACK_SUBDOMAIN` is not set.
## What is the expected behavior?
When standing up the backend, redis should not have this error.
## What steps did you take to get this behavior?
Make sure you don't have a backend server running.
Clone the frontend repo.
Run
`yarn run backend`
in another terminal tab:
`yarn start`

**Comment by rickr** [comment]
Can you provide the stacktrace?

**Comment by sethbergman** [comment]
You can see the stacktrace by running the following:
`yarn`
`yarn run backend`
`yarn start` in another tab, same directory

Then look at the tab you ran `yarn run backend`

I've already updated my local env so I can't at the moment.

**Comment by sethbergman** [comment]
https://github.com/OperationCode/operationcode_backend/blob/master/run/secrets/slack_subdomain

**Comment by sethbergman** [comment]
https://github.com/OperationCode/operationcode_backend/pull/129/files

**Comment by rickr** [comment]
The value doesn't matter and I'd prefer to not use a production value if able as that could lead to people in dev affecting prod. I think this would probably be a change to the Dockerfile but we'll need to see a stack trace to be sure.

I've also updated the steps to rep a bit as we don't have yarn on the backend.

**Comment by sethbergman** [comment]
Ok yeah just keep in mind this is all happening locally. I'm just reporting so that we can have dev / prod parity. If the value is not important, then you can go ahead and close this PR.

**Comment by sethbergman** [comment]
I've updated the replication steps. It must be run on the frontend.

**Comment by hpjaj** [comment]
@sethbergman - Is this still an active, backend issue, or can this be closed?

**Comment by sethbergman** [comment]
Absolutely! Thanks, this was from quite awhile ago when I was trying to figure out how to stage data on the backend locally.
