### ISSUE TITLE
Add team members to db seeds

### ISSUE THREAD

**Issue by sethbergman** [OperationCode/operationcode_backend#130]
# Bug Report
When running the backend locally, the staff are not being rendered on the team page.

## What is the expected behavior?
Staff / Volunteers are displayed

**Comment by rickr** [comment]
Since we used a rake task to populate production I think the easiest way to resolve this is to create some entries in `seeds.rb`.

**Comment by sethbergman** [comment]
What's the status on this? Is this something that can be done with some clear instructions? I'd love to see my name on the list, and I'd be happy to tackle this with some direction.

**Comment by sabrown84** [comment]
Is this one still open? @sethbergman I'd like to try this one did  you get any instructions?

**Comment by hpjaj** [comment]
@sabrown84 - To get you rolling, here are the two files that are being discussed:

- [seeds.rb](https://github.com/OperationCode/operationcode_backend/blob/master/db/seeds.rb)
- [team_member.rake](https://github.com/OperationCode/operationcode_backend/blob/master/lib/tasks/team_member.rake)

Ping me if you have any questions!

**Comment by coloradojay** [comment]
Any movement on this issue? If not, I'd love to get it going.

**Comment by sabrown84** [comment]
Hi @coloradojay, 

Sorry I had some stuff come up. I haven't made much head way. I am happy to pass the torch to you on this one. Enjoy.
