### ISSUE TITLE
Add Jobs endpoint

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/operationcode_backend#150]
# Feature
## Why is this feature being added?
Consolidate job resources behind our API by origin, so we can appropriately track who is applying for what category of job, the origin for each job, etc.

## What should your feature do?
Rough schema
* Job
 * Referral Origin
 * Job Title
 * Company
 * Description
 * Link to Role
 * Tags
 * Date Posted
 * Date Updated

**Comment by sethbergman** [comment]
I think that this sounds perfect for the jobs repo. However we'd still need to have the endpoint for the database. I'm leaning towards using graphQL in that repo. I'd like to define the schema on the front end, validate then POST. Is it possible to make the backend accept schemas without knowing all of the needed constructs? Maybe an empty list with slots available for data. I have no idea how to do this in Rails.

**Comment by hollomancer** [comment]
I'll defer to @rickr on his recommendations here. It will be important to associate individual users with jobs applied for, jobs clicked, etc.

**Comment by hollomancer** [comment]
This can wait.
