### ISSUE TITLE
Mentor Requests Are Not Populating to Airtable

### ISSUE THREAD

**Issue by jjhampton** [OperationCode/operationcode_backend#155]
# Bug Report
## What is the current behavior?
Submitting the Mentor Request form from front-end at https://operationcode.org/mentor-request doesn't populate the Airtable with the request via the back-end API.

## What is the expected behavior?
It should submit the mentorship request form and populate the request to the [Airtable Mentor Request form ](https://airtable.com/tbl9uQEE8VeMdNCey/viwILQ8iI5D7vzYpg)

## What steps did you take to get this behavior?
Went to https://operationcode.org/mentor-request, submitted a mentor request via the form

## Additional Info
See front-end [issue 341](https://github.com/OperationCode/operationcode_frontend/issues/341)

**Comment by hpjaj** [comment]
@rickr @jjhampton - I don't see anywhere in the back or frontend repos where we are making a call to [Airtable's API](https://airtable.com/appSqQz7spgg0I1jQ/api/docs#curl/introduction).

I do see that in the former OperationCode repo, the ['operationcode-airtable' gem](https://github.com/OperationCode/operationcode/blob/master/old_site/Gemfile#L10) is being used.  

As such:

- is there a current process for the [airtable request form](https://airtable.com/tbl9uQEE8VeMdNCey/viwILQ8iI5D7vzYpg) linking back to our current site?  if yes, what is it?
- if not, should this be converted to a feature request for the backend to expose a new endpoint that populates Airtable with the passed mentor request?

**Comment by jjhampton** [comment]
Thanks for looking into this, @hpjaj .  

* re: 'is there a current process for the airtable request form linking back to our current site? if yes, what is it?' - Not that I'm aware of.  Sounds like the integration w/ the Airtable API  might have not been built in as a feature while the new site was set up?  I'm not very familiar with Rails anymore, but I scanned through the API `requests_controller.rb` and the rest of the back-end and didn't see any Airtable-related stuff.

* re: 'should this be converted to a feature request for the backend to expose a new endpoint that populates Airtable with the passed mentor request?' -  Seems like a new feature request *could* work,
but we just want to bypass the idea of populating Airtable, since we've talking about moving mentor service requests to populate on Discourse? (issues / milestones have not been created for that idea yet). Might be a better use of resources for our back-end team as we try to phase out Airtable. @rickr might be able to weigh in on this.

Short term fix, if we merge in [front-end PR 466](https://github.com/OperationCode/operationcode_frontend/pull/466), we can just link directly from our page to the Airtable form to let users populate Mentor Service Requests. Then we can revise our in-app form and back-end API to integrate (with either Airtable, Discourse, or anything else).

**Comment by hpjaj** [comment]
@jjhampton - Thanks.  I actually removed my comment.  Reason being, I mistakenly relied on GitHub's search feature, from an iPad.  It returned no results for anything airtable related.  

But after searching in sublime, it turns out there is [a background job](https://github.com/OperationCode/operationcode_backend/blob/master/app/jobs/add_user_to_airtables_job.rb) in the backend repo that pings airtable's API.  It is triggered by an `after_create` callback on `User`.  

I haven't dug in any further, but at first blush this does appear to be a bug, as you reported.

**Comment by hpjaj** [comment]
@jjhampton - as [you uncovered in Slack](https://operation-code.slack.com/archives/C04FASBU9/p1504552546000086), the `AddUserToAirtablesJob` [background job](https://github.com/OperationCode/operationcode_backend/blob/master/app/jobs/add_user_to_airtables_job.rb) creates a user in Airtable, not a mentor request.  

We would need a new feature request for that, or one for moving to Discourse as you described above.

**Comment by hollomancer** [comment]
@jjhampton @rickr, do we want to make the web interface for mentors invisible for now, and just go straight to Discourse implementation?

**Comment by hpjaj** [comment]
Closing this issue as it was originally thought there was a bug preventing the API call to Airtable.  When in fact, this functionality does not currently exist, and would/could be a future feature request.
