### ISSUE TITLE
Add the whenever gem for cron jobs

### ISSUE THREAD

**Issue by hpjaj** [OperationCode/operationcode_backend#163]
# Feature
## Why is this feature being added?

We need to be able to have recurring cron jobs ran, on our behalf.  For example, to hit GitHub's API, or the Meetup API, on a daily basis, to pull in current statistics or Meetup events.

The [whenever gem](https://github.com/javan/whenever) is a perfect tool to solve this.  

This issue will complete the implementation for https://github.com/OperationCode/operationcode_backend/pull/153

## What should your feature do?
- Install the whenever gem
- Write a shell script for it 
- Update the Dockerfile to call the script instead of the current CMD

**Comment by hpjaj** [comment]
@rickr - ping

**Comment by hpjaj** [comment]
@ohaiwalt - curious if this issue is something you’re able to do?
 
I can take care of installing the `whenever` gem.  Would need your assistance on the second two bullet points.

**Comment by hollomancer** [comment]
@hpjaj, would this implementation accomplish what you need?
 http://derekbarber.ca/blog/2015/09/10/scheduling-background-jobs-in-rails-using-sidekiq/

**Comment by hpjaj** [comment]
@hollomancer - Nice find.  The only issue is deploying the setup to the server.  It "seems" like we would need to do similar config, as what we would need for just using the Whenever gem by itself.

But I don't know.  That would be a question for @rickr or @ohaiwalt ?  

Whichever approach is easier for them to setup, I can take care of the rest.

**Comment by hollomancer** [comment]
I think that in this case, it would just be happening in the same pod as operationcode_backend, wouldn't it? That would skip items 2 and 3.

**Comment by hpjaj** [comment]
¯\_(ツ)_/¯

The part of the article I am unsure on is the *Deploying Your Background Jobs*, since we do not use capistrano.  

Are you thinking that we can just setup a `config/deploy.rb` file as they describe, merge to master and deploy, and it would just work?

If yes, then yes, this would be a great option.

**Comment by hollomancer** [comment]
I'm not familiar with Capistrano - but yeah, I would think we would call `whenever --update-crontab` somewhere like .travis.yml or bin/deploy

**Comment by hpjaj** [comment]
Yeah, that is the missing link for me, too.  @ohaiwalt ?

**Comment by hollomancer** [comment]
Let's go ahead and get what we need in terms of cronjobs specified - we can worry about the deployment piece afterwards.

**Comment by BRIMIL01** [comment]
Since the project already uses sidekiq would it be better to use something like https://github.com/moove-it/sidekiq-scheduler?

**Comment by robbkidd** [comment]
I agree with using more Sidekiq. I've had recent good experience with [sidekiq-cron](https://github.com/ondrejbartas/sidekiq-cron) and recommend it.

**Comment by BRIMIL01** [comment]
I can take this and add https://github.com/ondrejbartas/sidekiq-cron support if that is aligned with how we want to manage jobs in backend.

**Comment by wimo7083** [comment]
Assigning myself as placeholder for you. :)
