### ISSUE TITLE
Code Schools API ping receives 500 error

### ISSUE THREAD

**Issue by kylemh** [OperationCode/operationcode_backend#168]
# Bug Report
## What is the current behavior?
Fetching from the `code_schools` endpoint yields a 500 server error.

## What is the expected behavior?
Fetching from the `code_schools` endpoint should yield a 200 success notice and operationcode.org/code_schools should render properly.

## What steps did you take to get this behavior?
Open dev tools and go to operationcode.org/code_schools

### Operating System
Linux Fedora 23 and MacOS latest

### Browser
Chrome (59 and latest) and Firefox (latest)

**Comment by sethbergman** [comment]
I noticed that this got merged without passing CI build:
https://github.com/OperationCode/operationcode_backend/pull/164

I'm wondering if this could be the root of the problem. :thinking:

**Comment by kylemh** [comment]
Fixed in #171 

@sethbergman called it!
