### ISSUE TITLE
Support MOOCs on the code school resource/model/table

### ISSUE THREAD

**Issue by caleywoods** [OperationCode/operationcode_backend#169]
# Feature
## Why is this feature being added?
[This issue](https://github.com/OperationCode/operationcode_frontend/issues/381) on the front-end calls for MOOCs to stop being hardcoded and be returned as JSON from the API like most, if not all, of everything else.

Per some conversation on the front-end issue, we think the existing [code school](https://github.com/OperationCode/operationcode_backend/blob/master/app/models/code_school.rb) model can support MOOCs by adding an `isMooc` boolean via a migration.

## What should your feature do?
This is a multi-step feature request, please let me know if each of the two parts should be seperated into an issue by themselves. I do not see any written tests that cover the code school model/resource, please let me know if I've overlooked those and a third bullet point needs added that covers writing tests for the new column.

* Add a migration to add `isMooc` as a boolean to the code school table
    * Make sure the code school model is aware of this new column
* Add a method to the code school controller that finds all code schools where `isMooc` is true and returns JSON

I am comfortable tackling this if those in charge of op code back-end are comfortable with it. I have some RoR experience but it has been several years since I worked in an active Rails codebase. I also plan on doing the front-end pull request once this is complete.

**Comment by hollomancer** [comment]
@caleywoods, all yours!

**Comment by hpjaj** [comment]
@caleywoods - How goes?  Any questions for us?

**Comment by hpjaj** [comment]
@caleywoods - As there has not been a pull request, or any recent activity on this issue, we are assuming it has become abandoned.  We are marking it available for other members to contribute.

Here are [our contributing guidelines](https://github.com/OperationCode/operationcode/blob/master/CONTRIBUTING.md#guidelines-for-working-an-issue) which discuss the process and **timelines** for working an issue.  You are more than welcome to re-reserve the issue, if it remains marked as "Status: Available"!
