### ISSUE TITLE
Update the CodeSchool :index and :show endpoints to yield the expected JSON

### ISSUE THREAD

**Issue by hpjaj** [OperationCode/operationcode_backend#174]
# Feature
## Why is this feature being added?

New `CodeSchool` and `Location` models [have been created](https://github.com/OperationCode/operationcode_backend/pull/164), with accompanying code school CRUD endpoints; however, two of the new endpoints are not returning the JSON structure the frontend expects.

## What should your feature do?
- Update the `api/v1/code_schools_controller#index` and `#show` actions to deliver a JSON payload whose **shape** is in keeping with what the frontend is expecting.
- For the `index` action we’ll want it to look like this:  https://github.com/OperationCode/operationcode_backend/blob/master/apiary.apib#L14-L39
- For the `show` action, we’ll want it to look like that also, but with just *one* location. 
- Update the [API documentation](https://github.com/OperationCode/operationcode_backend#api-documentation)

**Comment by PrimeTimeTran** [comment]
@hpjaj I'll take this one.

**Comment by hpjaj** [comment]
@PrimeTimeTran - It's yours!

**Comment by hpjaj** [comment]
Moving this discussion to the issue:

@hollomancer @kylemh @jjhampton @Cooperbuilt - What payload do you want the `:show` endpoint to deliver?

1 - a single school at **one** location, or 
2 - a single school, with all its locations

For option 1 we would have the frontend pass two params in the request, a school and a location.

For option 2, it would just pass the school.

**Comment by PrimeTimeTran** [comment]
@hpjaj thanks for moving it forward =), currently blocked on this after having completed the other requests for tests & refactoring.

Guys, I don't know which one to return if a *CodeSchool* has multiple locations. Obviously, this won't be an issue for a *CodeSchool* with one location but there are a few with multiple.

**Comment by kylemh** [comment]
@PrimeTimeTran returning all locations sounds best! Harry and I had a convo about it on Slack. 

Aka: option 2 on Harry's above comment.

**Comment by PrimeTimeTran** [comment]
@kylemh I think this should be resolved with PR #176

**Comment by hpjaj** [comment]
Completed in https://github.com/OperationCode/operationcode_backend/pull/176
