### ISSUE TITLE
Research: Make it easier to query our database for user information

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/operationcode_backend#175]
# Feature
## Why is this feature being added?

Make it easier to query our database for user information

## What should your feature do?
Creates an admin dashboard that is only accessible to specific users.  

- [x] On the `User` page, it should provide a broad filtering mechanism to query for any number of one-off criteria, based on the `User` tables attributes
- [x] Can create, edit, view and/or delete `User`s
- [x] Can create, edit, view and/or delete `AdminUser`s

On the `User` page, it should be able to filter users by:
- [x] mentor
- [x] state
- [x] verified status

On the main dashboard, it should display
- [x] How many users today
- [x] How many users over last week
- [x] How many users over last month
- [x] How many users over last year
- [x] Number of verified users

Future feature: We’d need to define regions, then filter by those on the `User` page

### Background

Was looking at some dashboards for this
https://www.forestadmin.com/

**Comment by hollomancer** [comment]
@hpjaj, I'm of the mindset that until we have a good way to query user data, do searches, etc. for non-technical users, there's not much point in getting too elaborate with a lot of these other tickets. My preference would be to do this from Slack via a bot, but a web dashboard is fine too if it's easier.

**Comment by hpjaj** [comment]
@hollomancer - Sweet find.  

Another option is [ActiveAdmin](https://www.activeadmin.info/).  I have some experience with it.  It is not the sexiest choice out there, but it has been around a while, so the assumption would be that others would have some experience with it, too.  Also, it is stable and actively maintained.  

The only variable is, how would the hosting work?  I am not sure on the logistics of getting that stood up.  But outside of that, it is pretty powerful.

If you play around with [the demo](http://demo.activeadmin.info/admin), do you feel that it would give you the type of data that you would be interested in?

**Comment by hollomancer** [comment]
I think this could do the job - my primary priority is something open source that's 'drop in' and that we don't have to spend a huge amount of time maintaining.

**Comment by sethbergman** [comment]
You may want to check out auth0. They have a full suite for authentication, user profiles (social) and API integrations (Slack) that I think would be useful for you. I just sent you an invite to a trial, and built a test app @hollomancer.

https://manage.auth0.com

![image](https://user-images.githubusercontent.com/8031689/31559804-95af9b3c-b017-11e7-9ff8-1b5aa3814190.png)

Here's the repo. It's running the same version of React, so it wouldn't be hard to integrate with the frontend if it's something you like. I'm about to see if I can get it deployed real quick.

https://github.com/sethbergman/react-auth-multi

**Comment by kylemh** [comment]
@sethbergman The only problem is that it's not inherently free. I do love Auth0's stuff - maybe they'd consider a freebie for us?

**Comment by sethbergman** [comment]
Well the other route is the passport middleware for Express. It essentially does the same stuff as far as authentication with social providers, but the data it returns is up to us to graph all nicely. :smile_cat: 
And yes, I don't think it would hurt to see if we could get a special deal as a non-profit with such a kick ass mission.

**Comment by kylemh** [comment]
@sethbergman I'm confused now. I think this issue is about creating an admin data dashboard to visualize data. It's not about authorization. I was okay with Auth0 cuz I know they provide that service.

**Comment by hollomancer** [comment]
@kylemh, you are correct. This particular issue is about creating an admin data dashboard to visualize data.

**Comment by hpjaj** [comment]
I'll work on getting a PR up using ActiveAdmin

**Comment by hollomancer** [comment]
Looks like https://github.com/sferik/rails_admin and https://github.com/thoughtbot/administrate are also options.

**Comment by sethbergman** [comment]
Sorry if I was unclear. I was just pointing out the free option, which doesn't help here at all. I believe @kylemh had some questions about Passport in a prior ticket. I've been busy configuring my localhost with minikube, and didn't mean to get off topic, but I always do.
