### ISSUE TITLE
Update Sabio logo url in `code_schools.yaml`

### ISSUE THREAD

**Issue by kylemh** [OperationCode/operationcode_backend#178]
# Feature
## Paired Issue
Please note this issue requires simultaneous resolution with https://github.com/OperationCode/operationcode_frontend/issues/690

## Why is this feature being added?
We're changing the Sabio logo on the front-end from `.jpg` to `.png`. The change will need to be reflected in `code_schools.yaml` in order to properly render from `/code_schools` API calls.

## What should your feature do?
Change the last 3 characters of [this line](https://github.com/OperationCode/operationcode_backend/blob/master/config/code_schools.yml#L139) to `.png`

**Comment by shawnlknight** [comment]
I'd love to take this issue and the frontend issue as well!

**Comment by hpjaj** [comment]
@shawnlknight - it is yours!  When you submit your pull request, please be sure to mention/remind  that there needs to be coordinated deployment between the front and backends.
