### ISSUE TITLE
Add tests against Apiary/Dredd to CD/CI

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/operationcode_backend#180]
# Feature
## Why is this feature being added?
Ensure our documentation is always in alignment with our API implementation.

## What should your feature do?
Our docs at http://docs.operationcodeapi.apiary.io/# should take advantage of Travis to verify that new pull requests are appropriately documented.

Instructions: https://help.apiary.io/tools/automated-testing/testing-ci/

**Comment by kirbygit** [comment]
I would love to do this on my freetime with some guidance

**Comment by michizhou** [comment]
@hollomancer If it's alright, I would be happy to tackle this issue with some guidance!

**Comment by kylemh** [comment]
@robbkidd @wimo7083 👀

**Comment by wimo7083** [comment]
Setting myself as placholder.

**Comment by hollomancer** [comment]
Defer for now until backend roadmap is clearer
