### ISSUE TITLE
Remove all squad related code as the frontend no longer needs it

### ISSUE THREAD

**Issue by hpjaj** [OperationCode/operationcode_backend#184]
# Feature
## Why is this feature being added?

Per the discussion in https://github.com/OperationCode/operationcode_frontend/pull/698, the frontend is no longer using any squad related code.  As such, this code is no longer needed and should be removed to reduce code bloat and potential confusion to future contributors. 

## What should your feature do?
Do a full search through the backend for `squad`, and remove any associated code and files.  Here are some of the primary files:

```
squad.rb
squad_member.rb
squad_mentor.rb
squads_controller.rb
squad tests
squad related code in seeds.rb
```

And potentially more.

**Comment by ianroberts131** [comment]
I'll take a look at this today

**Comment by hpjaj** [comment]
@ianroberts131 - its yours!
