### ISSUE TITLE
Endpoints to create, update and delete a `Location` associated with a `CodeSchool`

### ISSUE THREAD

**Issue by hpjaj** [OperationCode/operationcode_backend#185]
# Feature
## Why is this feature being added?

We currently have endpoints that will do all the CRUD actions for the `CodeSchool` model; however, a code school is incomplete without an accompanying `Location`.

For example, one code school might have one or multiple locations, spread across the country.

## What should your feature do?
- [ ] Create a `Location` `create` endpoint
- [ ] Create a `Location` `update` endpoint
- [ ] Create a `Location` `delete` endpoint
- [ ] Applicable test coverage
- [ ] Add [API documentation](https://github.com/OperationCode/operationcode_backend#api-documentation) for all three endpoints

There are many examples of this in the backend repo to go off of.  Here are a few from the [team_members_controller](https://github.com/OperationCode/operationcode_backend/blob/master/app/controllers/api/v1/team_members_controller.rb).

**Comment by codyborders** [comment]
@hpjaj I'll give this one a try!

**Comment by hpjaj** [comment]
@codyborders - Its yours!  Ping me if you have any questions on it (@harry on our Slack channel).

**Comment by hpjaj** [comment]
@codyborders - How goes?  Any questions for us?

**Comment by hpjaj** [comment]
@codyborders - As there has not been a pull request, or any recent activity on this issue, we are assuming it has become abandoned.  We are marking it available for other members to contribute.

Here are [our contributing guidelines](https://github.com/OperationCode/operationcode/blob/master/CONTRIBUTING.md#guidelines-for-working-an-issue) which discuss the process and **timelines** for working an issue.  You are more than welcome to re-reserve the issue, if it remains marked as "Status: Available"!
