### ISSUE TITLE
Add Cincy Code IT Boot Camp to code_schools.yaml

### ISSUE THREAD

**Issue by kylemh** [OperationCode/operationcode_backend#190]
# Feature
## Why is this feature being added?
We were emailed by staff at MAX Careers asking to be featured on our /code_schools page.

They're reportedly VA-approved, and they do not offer an online program.

https://maxtrain.com/career/

## What should your feature do?
Implement a yaml object for `Cincy Code IT Boot Camp` with the appropriate information filled out.

**Comment by whuang8** [comment]
Hi, I can work on this issue.

**Comment by kylemh** [comment]
@whuang8 all yours!

**Comment by whuang8** [comment]
@kylemh I can't seem to find an email address on their site. Do you have one that I can use in the yaml file for Cincy Code IT Boot Camps?
