### ISSUE TITLE
Create object for SecureSet in code_schools.yaml

### ISSUE THREAD

**Issue by kylemh** [OperationCode/operationcode_backend#196]
# Feature
## Why is this feature being added?
SecureSet is an amazing partner, and also a Cyber Security Bootcamp. They've requested to be listed on our /code_schools page.

## What should your feature do?
Add SecureSet to ./config/code_schools.yaml in observation of rules set out in the top of that file.

**VA-Approved** 
**Notes:** Not a traditional coding bootcamp. SecureSet focuses on security training relevant to the IT industry.
**Locations:** 
- Colorado Springs, CO 
- Denver, CO 
**Website:** https://secureset.com/

**Comment by unmonk** [comment]
Doing this,  do you have the logo in front_end yet?

**Comment by hpjaj** [comment]
Completed in https://github.com/OperationCode/operationcode_backend/pull/198
