### ISSUE TITLE
Running `make setup` on initial repo setup throws error

### ISSUE THREAD

**Issue by hpjaj** [OperationCode/operationcode_backend#20]
# Bug Report
## What is the current behavior?
When initially setting up this repo locally, the following error is generated when running the `make setup` command.

```
➜  operationcode_backend git:(master) make setup
docker-compose run web rake db:create
Pulling bundle (operationcodebackend_web:latest)...
ERROR: repository operationcodebackend_web not found: does not exist or no pull access
make: *** [db_create] Error 1
```

## What is the expected behavior?
According to the [Makefile](https://github.com/OperationCode/operationcode_backend/blob/master/Makefile#L42) a successful `db_create db_migrate`

## What steps did you take to get this behavior?
1. Clone the repo; `cd` into it
2. `$ bundle`
3. `$ make setup`

### Operating System
macOS Sierra 10.12.4

**Comment by alexspence** [comment]
Problem is we need to build the docker containers before running make setup.
```
make build
make setup
```

Works.

We can either document that this is the process, or add build to the `make setup` via Makefile
