### ISSUE TITLE
Create flow for new contributors to get a Cloud9 account

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/operationcode_backend#203]
# Feature
## Why is this feature being added?
In order to make it easier for new contributors to get set up, I'd like to get them a Cloud 9 account. Because we use C9 for Education, we could provide a prebuilt development environment for everyone who wants to get into open source!

This issue is for brainstorming.

## Notes
https://community.c9.io/t/invite-team-users-via-an-api/12970/13
https://github.com/kinoshitajona/c9addmember

**Comment by hollomancer** [comment]
Not a high priority.

**Comment by wimo7083** [comment]
No longer possible.
