### ISSUE TITLE
Request add endpoint to get user's verified state. 

### ISSUE THREAD

**Issue by wimo7083** [OperationCode/operationcode_backend#216]
# Feature: New Apiary Endpoint to request user information
## Why is this feature being added?
Currently [pybot](https://github.com/OperationCode/operation_code_pybot) provides new slack members with useful resources. per front end issue [#765](https://github.com/OperationCode/operationcode_frontend/issues/765 ). Only members who are verified veterans are eligible for certain resources ex: mentorship, and veterans scholarships. We shouldn't offer these resources to individuals who don't qualify. 

I'd like to be able to get an endpoint in which I can take a registered user information which is connected to a slack id to user information. Additionally there are other sections within the [User Table](https://github.com/OperationCode/operationcode_backend/blob/master/db/schema.rb#L184-L225) that would be helpful if exposed (mentor, details about service, interests and contact information). 

Since this is being requested by an external program some of these details might be important to keep secure. I'm unsure if the API is public facing or if we need to make a way for only registered applications/ requests to get the information.

**Comment by liambarstad** [comment]
Hey there, myself and @MiguelSilva1997 are first time contributors and would like to tackle this issue, is it still available?

**Comment by wimo7083** [comment]
Hi there, it's currently in progress as seen here:
https://github.com/OperationCode/operationcode_backend/pull/240

I'm new to ruby, and the current Project Lead has exciting personal things keeping him away from this project. If you'd like to look over what I've done you're more than welcome to add onto it. 

The current things that are in progress are making the endpoint more secure than a global variable, I also need to include exception handling for the database access and any other good practices in ruby.

**Comment by liambarstad** [comment]
we'd love to talk more, is there a workspace we can join?

**Comment by wimo7083** [comment]
Hi yeah, come join us here: https://operationcode.org/signup

**Comment by wimo7083** [comment]
I want make sure you know you don't have to be a vet or related to vet, we have many members who just want to contribute and looking for an easy place to communicate.

**Comment by hpjaj** [comment]
@OperationCode/issues-team - Is this issue part of the current roadmap?  If so, can we layout exactly what pain point we are trying to resolve, and confirm that this is the best way to accomplish that.  Otherwise, I am not sure we want to expose the backend API in this manner.

**Comment by kylemh** [comment]
@wimo7083 prolly best to describe some examples that pybot could run through provided it had eyes on user details.

**Comment by wimo7083** [comment]
In the PR I mentioned a few examples of things I would like to do: PR #240 

The three primary reasons I see this as helpful.

1. I'd like to be able to get verified status from the backend to serve additional content, currently the slackbot is used to handle the mentor notification system. We currently have routes to get to the mentor request that don't require verification. I want to eliminate that, and make a simple interface for mentor request within slack. 
2. For the longest time when people join slack we've offered a choice of resources. Currently it's this list:
![image](https://user-images.githubusercontent.com/10781353/37260161-4b027f60-2555-11e8-9227-ea286fb9777a.png) 
When members join we ask them what they are interested in, and then ignore those items and tell them to look at ruby, python and whatever has been there for over a year. As we are trying to support all tech careers I'd like to use the information that people gave us and offer them resources. 
3. Lastly, if someone joins slack it's not tied to the backend database. Part of this route that I'm setting up takes a verified user signup and connects the slack signup to the backend signup. In the future this means that we can politely send them an email that reminds people who don't sign up about our slack community. 

To me, this request seems to solidly fall in line with our mission statement, and if we can come up with some kind of authentication solution we should be able to minimize the exposure of the backend api.

**Comment by nellshamrell** [comment]
While I can certainly see the use of this feature, my main concern is whether this information will be exposed publicly.  Because there is personal information included in it - I would only be open to this if there were some sort of auth required to access the API.  This is not on our current road map (which will be released soon!) - I'd rather do the verification of whether someone is a veteran after they request the resource, rather than determining it before showing them the resources that are available.    That said, I am certainly open to other opinions on this.

**Comment by wimo7083** [comment]
Auth would be required, if you have any suggestions on my contribution I'll definitely take them.

I agree that any data should be kept private and subject to any security policy you state.

The veteran status was to help people in that awkward scenario in which they had to ask and deny services when someone didn't qualify. 

Looking through the old Issues I also see that #37 lines up pretty well with this change. We currently notify members when people join. Getting the zipcode from backend and finding a community leader would be fairly easy and keep it all in slack. 

Additionally there's already issues in frontend for a map that's going to require a similar endpoint for all user location and event location for all events.

**Comment by hpjaj** [comment]
I'll explore some authentication options to secure our API, for non-user consumers (i.e. Slack).

**Comment by wimo7083** [comment]
Thanks. If you give me the requirements. I can do the footwork.

**Comment by hpjaj** [comment]
Closing this out in favor of the Slack integration issues 1 - 6
