### ISSUE TITLE
Add API Documentation for Mentors, Services and Status endpoints

### ISSUE THREAD

**Issue by hpjaj** [OperationCode/operationcode_backend#217]
# Feature
## Why is this feature being added?

Our contributors need to be able to research, confirm and build against the API endpoints that the backend offers.

## What should your feature do?
Document the following backend API endpoints in our [online API documentation](https://operationcodeapi.docs.apiary.io/#).  When doing so, **please follow** the steps described in our `README` for [how to document our API](https://github.com/OperationCode/operationcode_backend#api-documentation).

The endpoints to be documented are:

- [ ] `api/v1/mentors_controller#index`
- [ ] `api/v1/mentors_controller#show`
- [ ] `api/v1/services_controller#index`
- [ ] `api/v1/status_controller#all`

**Comment by dave5801** [comment]
@hpjaj May I have this issue -- i think this would be great starting point on the backend.

**Comment by hpjaj** [comment]
@dave5801 - It's yours!  Ping me if you have any questions.

**Comment by robotscissors** [comment]
HI @hpjaj, I am new to contributing and it looks like this is up my alley. May I?

**Comment by hpjaj** [comment]
@robotscissors - it's yours!  Let me know if you have any questions.

**Comment by robotscissors** [comment]
Hi Harry, got docker installed and forked. Following the instructions [
operationcode_backend/docs/setup/docker_setup.md], after running this:

Let's Go:> make test


docker-compose up --build -d

Creating network "operationcodebackend_default" with the default driver

Pulling bundle (operationcodebackend_web:)...

ERROR: Get
https://registry-1.docker.io/v2/library/operationcodebackend_web/manifests/latest:
unauthorized: incorrect username or password

make: *** [bg] Error 1

Can you give me a shove in the right direction?

**Comment by hpjaj** [comment]
To confirm, have you tried:

1. Have the Docker app running
2. Run `make setup`
3. Run `make bundle`
4. Run `make test`

**Comment by hpjaj** [comment]
Also, are you on a Mac, PC, or Linux?

**Comment by robotscissors** [comment]
Hi Harry,
I am on a Mac. Yes, I have tried all three commands and docker is running.

https://registry-1.docker.io/v2/library/ruby/manifests/2.3.3  (which I
think is the container)

Returns this:
{

   - errors:
   [
      -
      {
         - code: "UNAUTHORIZED",
         - message: "authentication required",
         - detail:
         [
            -
            {
               - Type: "repository",
               - Class: "",
               - Name: "library/ruby",
               - Action: "pull"
               }
            ]
         }
      ]

}

**Comment by robotscissors** [comment]
Hold the phone. I logged out of Docker at the command line and logged back in again, and things are moving. Thank you for your patience.
