### ISSUE TITLE
Add API Documentation for Resources and Sessions endpoints

### ISSUE THREAD

**Issue by hpjaj** [OperationCode/operationcode_backend#220]
# Feature
## Why is this feature being added?

Our contributors need to be able to research, confirm and build against the API endpoints that the backend offers.

## What should your feature do?
Document the following backend API endpoints in our [online API documentation](https://operationcodeapi.docs.apiary.io/#).  When doing so, **please follow** the steps described in our `README` for [how to document our API](https://github.com/OperationCode/operationcode_backend#api-documentation).

The endpoints to be documented are:

- [ ] `api/v1/resources_controller#destroy`
- [ ] `api/v1/sessions_controller#create`

**Comment by christopher-wolff23** [comment]
@hpjaj I'm going to try to do this one, get to know the backend a bit better.

**Comment by hpjaj** [comment]
@christopher-wolff23 - it's yours!

**Comment by hpjaj** [comment]
@christopher-wolff23 - In case you're interested, here are a few closed PR's that are similar, that you can use for reference:

- https://github.com/OperationCode/operationcode_backend/pull/229
- https://github.com/OperationCode/operationcode_backend/pull/231
- https://github.com/OperationCode/operationcode_backend/pull/224

**Comment by christopher-wolff23** [comment]
Thanks for those resources. I will try to resolve this one by the end of
this week. Got sidetracked trying to learn ruby, rails, and apiary.

**Comment by hpjaj** [comment]
@christopher-wolff23 - As there has not been a pull request, or any recent activity on this issue, we are assuming it has become abandoned. We are marking it available for other members to contribute.

Here are our [contributing guidelines](https://github.com/OperationCode/operationcode/blob/master/CONTRIBUTING.md#guidelines-for-working-an-issue) which discuss the process and timelines for working an issue. You are more than welcome to re-reserve the issue, if it remains marked as "Status: Available"!

**Comment by christopher-wolff23** [comment]
@hpjaj Sorry! I had some initial trouble wrapping my head around Rails, and then school started back again. Hopefully I'll find some time to look at it, again. But it's fine that you made it available.

**Comment by hpjaj** [comment]
@christopher-wolff23 - No worries!

**Comment by nagano564** [comment]
K... I will check this out on thursday to see if I have any shot of handling this. @hpjaj Let's see how it goes. If I can't figure it out I will just bug the crap out of my mentor.

**Comment by hpjaj** [comment]
@nagano564 - It's yours!  Let me know if you run into any issues.

**Comment by hpjaj** [comment]
@nagano564 - Heads up, updated this story's acceptance criteria.
