### ISSUE TITLE
Add API Documentation for Users endpoints

### ISSUE THREAD

**Issue by hpjaj** [OperationCode/operationcode_backend#221]
# Feature
## Why is this feature being added?

Our contributors need to be able to research, confirm and build against the API endpoints that the backend offers.

## What should your feature do?
Document the following backend API endpoints in our [online API documentation](https://operationcodeapi.docs.apiary.io/#).  When doing so, **please follow** the steps described in our `README` for [how to document our API](https://github.com/OperationCode/operationcode_backend#api-documentation).

The endpoints to be documented are:

- [ ] `api/v1/users_controller#create`
- [ ] `api/v1/users_controller#update`
- [ ] `api/v1/users_controller#verify`

**Comment by wimo7083** [comment]
I'd like to work on this one.

**Comment by hpjaj** [comment]
@wimo7083 - all yours!
