### ISSUE TITLE
Authenticate user in CodeSchool create, update, and destroy endpoints

### ISSUE THREAD

**Issue by hpjaj** [OperationCode/operationcode_backend#239]
# Feature
## Why is this feature being added?

Currently the endpoints to `:create`, `:update`, and `:destroy` a `CodeSchool` record are unprotected, and do not require user authentication.

## What should your feature do?
- [ ] Add a `before_action :authenticate_user!` check in the [CodeSchool controller](https://github.com/OperationCode/operationcode_backend/blob/master/app/controllers/api/v1/code_schools_controller.rb) for the `:create`, `:update`, and `:destroy` actions
- [ ] update the API docs 
- [ ] update the associated tests

**Comment by alexbeeken** [comment]
@issues-team Hi guys. PR up for this: #244! I wasn't sure if I had time so I didn't reserve it ahead of time. I'll be sure to do that in the future.

**Comment by hpjaj** [comment]
@alexbeeken - Fantastic...thanks for the PR!

**Comment by alexbeeken** [comment]
@hpjaj I see that some of my tests are causing errors. Forgive my ignorance but how do you run individual tests on your docker setup?

**Comment by hpjaj** [comment]
@alexbeeken - No worries.  It is not totally straight forward.  Here you go:  https://github.com/OperationCode/operationcode_backend/wiki/Testing-One-File
