### ISSUE TITLE
Add Skill Distillery to Code Schools

### ISSUE THREAD

**Issue by ksmacleod99** [OperationCode/operationcode_backend#241]
##Why is this feature being added?
Please add [Skill Distillery](skilldistillery.com) to Code School list.

##What should your feature do?
VA-Approved: Yes
GI Bill Accepted: Yes
Commitment: Full time
Hardware Included: no

**Comment by hpjaj** [comment]
I'll add this in once I get access to prod's rails console.  Should be soon.

**Comment by hpjaj** [comment]
I added these via prod's `rails c`
