### ISSUE TITLE
Allow non-US zip codes for volunteers

### ISSUE THREAD

**Issue by nellshamrell** [OperationCode/operationcode_backend#242]
Hello!

We have a developer in the U.K. who is interested in contributing to our open source projects.  He attempted to join our org as a volunteer, but we only accept U.S. zip codes.  We should consider accepting non-U.S. zip codes for volunteers.

**Comment by jjhampton** [comment]
In addition to any back-end changes, the front-end [FormZipCode](https://github.com/OperationCode/operationcode_frontend/blob/0cba7ebd242c19434b09321e31ac3f3ed5021352/src/shared/components/form/formZipCode/formZipCode.js) React component will also need to be changed to allow this. It currently runs form validation via regex.

**Comment by alexbeeken** [comment]
@nellshamrell I'm claiming this! Going to do the frontend too.

**Comment by alexbeeken** [comment]
@nellshamrell The solution seems to be to ask Geocoder if it can find the zip code on form submission. If it can't, I simply return "zip code: not found". I removed the frontend validation regex and simplified it to just check if there is actually input in the field. PRs coming up soon.

**Comment by alexbeeken** [comment]
Connects to this too https://github.com/OperationCode/operationcode_frontend/pull/840

**Comment by ag-kylemh** [comment]
@alexbeeken any update?

**Comment by kylemh** [comment]
@alexbeeken any update?

**Comment by alexbeeken** [comment]
@kylemh just updated the PR. Ready for review again! Sorry for the delay.
