### ISSUE TITLE
Add Team table group functionality

### ISSUE THREAD

**Issue by wimo7083** [OperationCode/operationcode_backend#243]
# Create a new column for Team database
## Why is this feature being added?

Currently we treat all team members as general members, and when promotion/ demotion we have to remove from database and statically add them to front end. This change would make it so we can have different class of members for our team

We can then add legacy members, board members, and general members and allow the front end to decide how to render while correctly tracking their state instead of removing from database. 

## What should your feature do?
Modify schema to include this column
Migrate database to new schema
Include board members who are not currently tracked.

**Comment by alexbeeken** [comment]
@wimo7083 Hey William, I'm wondering how this would be different than the already existing `role` column?

**Comment by wimo7083** [comment]
https://operationcode.org/team

We currently have two groups for team members displaying. Right now if someone goes from a `team_member` to a `board` member they need to be removed from the database. Otherwise they appear twice ex:  tyrone grandison. 

Right now the role is the displayed text.

**Comment by alexbeeken** [comment]
@wimo7083 okay I'm going to take a stab at this today.

**Comment by alexbeeken** [comment]
The PR should be ready for review! 👍
