### ISSUE TITLE
Correct information for General Assembly in Code Schools

### ISSUE THREAD

**Issue by nellshamrell** [OperationCode/operationcode_backend#253]
From a staffer at General Assembly:

"I recently came across your site https://operationcode.org/code_schools
and noticed that you do not have the most recent information on our acceptance of the GI Bill here.

Could you please update the information on the page to reflect that we accept the GI Bill for these programs in NY and DC:

NY: Web Development Immersive, User Experience Design Immersive
DC: Web Development Immersive, User Experience Design Immersive, Data Science Immersive

We'll be adding to this over time, but could you add that information, linking back here:

https://generalassemb.ly/gi-bill?utm_medium=affiliate-lead-gen-global&utm_campaign=2018-q1-affiliate-lead-gen-global-operation-code-affiliate&utm_source=operation-code   

Please let me know if you have any questions."

**Comment by hpjaj** [comment]
@nellshamrell - I made the updates directly in prod's db.  Done.

cc: @kylemh

**Comment by nellshamrell** [comment]
Thank you so much, @hpjaj!
