### ISSUE TITLE
Code Platoon VA Approved!

### ISSUE THREAD

**Issue by JYoung217** [OperationCode/operationcode_backend#255]
# Feature
## Why is this feature being added?
Code Platoon was approved by the VA on Friday for the GI Bill. We are updating our records with Operation Code to reflect that.

## What should your feature do?
We should show up under the "VA-Approved Schools" section and all the cards where Code Platoon is featured in should have "GI Bill Accepted: True" written.

**Comment by hpjaj** [comment]
@JYoung217 - I updated this in prod's db!
