### ISSUE TITLE
Endpoint to populate airtable with data from the FE 'Mentor Request Form'

### ISSUE THREAD

**Issue by AshTemp** [OperationCode/operationcode_backend#259]
# Feature
## Why is this feature being added?
The FE has the beginnings of a "Mentor Request Form" in [mentorRequest.js](https://github.com/OperationCode/operationcode_frontend/blob/master/src/scenes/home/mentorRequest/mentorRequest.js).  This form will only be accessible to ID.me verified users.  This data needs to ultimately be populated in Airtable's in our mentorship airtable.

## Associated Issues

- https://github.com/OperationCode/operationcode_frontend/issues/890#issuecomment-370988070
- https://github.com/OperationCode/operationcode_backend/issues/155#issuecomment-327019601

## What should your feature do?

- [x] create a `POST` endpoint that hits Airtables API and populates our mentorship airtable with the passed data: 
  - mentee's slack user name
  - an array of service ids
  - an array of skillset names
  - additional details text
  - a mentor's id (or full name?)
- [x] validation that the passed `user` is verified
- [x] test coverage
- [x] updates our API docs
- [ ] collaboration with the FE team on the endpoint's schema (i.e. what they are sending to the BE)
- [x] creates a `GET` endpoint that returns the following lists of information from Airtable
  - list of service ids and names
  - list of mentor full names and ids
  - list of skillset ids and names
- [ ] Remove the Operationcode::Airtable gem
- [ ] Replace any Operationcode::Airtable gem code with new client implementation

**Comment by nagano564** [comment]
can I take a stab at this @AshTemp @hpjaj

**Comment by nagano564** [comment]
Can I take a stab at this @AshTemp @hpjaj

**Comment by AshTemp** [comment]
It's fine with me, I just report the things I need y'all make the magic happen.

**Comment by hpjaj** [comment]
@AshTemp - I need to sync up with you to iron out this issue.  In the meantime, I'm going to place this issue on hold.

cc: @nagano564

**Comment by AshTemp** [comment]
I'm always around, just shoot me a DM on slack.

**Comment by hpjaj** [comment]
@AshTemp - I have updated this issue...ready for a contributor!

**Comment by hpjaj** [comment]
@kylemh @jjhampton - Will the user be able to select one or multiple choices for these two inputs:

https://github.com/OperationCode/operationcode_frontend/blob/master/src/scenes/home/mentorRequest/mentorRequest.js#L112-L135

Will the FE will be passing one item, or a list of items, for those two inputs?
