### ISSUE TITLE
Add instructions for running the dev environment in a VM

### ISSUE THREAD

**Issue by nellshamrell** [OperationCode/operationcode_backend#271]
I was recently working with a member who's computer could not run Docker.  We worked together on figuring out how to use an AWS instance to run his dev environment in.  

I've written up the instructions here https://gist.github.com/nellshamrell/5a2843605d8478357175c514d53c3da6

Getting these into the README would be a great first time contribution!

**Comment by kirbygit** [comment]
ill try to do this once I get back home nell cc @kirbygit

**Comment by dave5801** [comment]
@nellshamrell May I have this issue? Since I was the member you speak of. This would be a great first time contribution!

**Comment by kirbygit** [comment]
this issue is being done on the pull request #272

**Comment by kirbygit** [comment]
@dave5801 hey you can go ahead and claim this issue and basically just copy the pr I did. I won't mind

**Comment by hpjaj** [comment]
@kirbygit - it's yours!

**Comment by kirbygit** [comment]
PR #282 fixes this issue now thanks.
