### ISSUE TITLE
Add `is_partner` boolean attribute to CodeSchool table

### ISSUE THREAD

**Issue by hpjaj** [OperationCode/operationcode_backend#275]
# Feature
## Why is this feature being added?

The frontend uses this descriptor for filtering on the code schools page.   We rarely seem to remove partner schools.  As such, it would make filtering easier if this attr was available as part of the endpoints responses, by default.

## What should your feature do?

- [x] Add `is_partner` to the `CodeSchool` table.  Defaulting to `false` and `null` `false`
- [x] Add attr to serializer
- [x] Add attr to strong params
- [x] Update apiary docs
- [ ] Add spec illustrating presence
- [x] Add attr to factory, default to `false`
- [ ] Creates a new `rake` task to set any existing, relevant `CodeSchool` records in prod to `is_partner: true`

**Comment by kylemh** [comment]
I like that you made a checklist this time. Idea: add it into `.github/PULL_REQUEST.md` for if a PR involving adding other code schools?

**Comment by kirbygit** [comment]
Can i try this and help me out :D @hpjaj ✌️

**Comment by hpjaj** [comment]
@kirbygit - It's yours!  Yeah, ping me if you run into any issues.

**Comment by hpjaj** [comment]
@kirbygit -  How goes?  Any progress on getting a PR in place?

**Comment by hpjaj** [comment]
@kirbygit  - As there has not been a pull request, or any recent activity on this issue, we are assuming it has become abandoned.  We are marking it available for other members to contribute.

Here are [our contributing guidelines](https://github.com/OperationCode/operationcode/blob/master/CONTRIBUTING.md#guidelines-for-working-an-issue) which discuss the process and **timelines** for working an issue.  You are more than welcome to re-reserve the issue, if it remains marked as "Status: Available"!

**Comment by nagano564** [comment]
Hey I'm gonna give it a go. 

a few questions:

The first point in the checklist. Which one should it default to false or null?

Defaulting to false and null false

**Comment by hpjaj** [comment]
@nagano564 - It's yours!

Here is a good explanation of that migration file question:

https://robots.thoughtbot.com/avoid-the-threestate-boolean-problem

**Comment by kirbygit** [comment]
is this issue being done I see a pr :)
