### ISSUE TITLE
Instructions on a native setup added to the readme

### ISSUE THREAD

**Issue by hpjaj** [OperationCode/operationcode_backend#278]
# Feature
## Why is this feature being added?

When using this repo locally, you can do so via Docker, a AWS VM, or through a native setup.  We currently have instructions for the first two, but not the latter.

## What should your feature do?
Create a set of instructions for setting up this repo natively.  Follows the pattern laid out in https://github.com/OperationCode/operationcode_backend/pull/277

**Comment by aamarill** [comment]
Hello @hpjaj can I get started on this issue? 😄

**Comment by hpjaj** [comment]
@aamarill - it's yours!

**Comment by aamarill** [comment]
@hpjaj I apologize for the delay on this!
If you see someone else looking for work, please have them give me a hand with this.
Feel free to update the "status" label to "available".

I don't think I am going to have too much spare time in the coming weeks.
Thanks! 😄

**Comment by aamarill** [comment]
@hpjaj So sorry for the delay on this, but I don't think I can work this anymore. I recommend that you please update the status to "available". In addition, you may want to add a "beginner friendly" tag 😅 
Thank you for the opportunity to contribute!

**Comment by robbkidd** [comment]
Would a hybrid native/docker/docker-compose development environment work? Wherein the Ruby bits—the web service running in development mode, minitest tests, rubocop, etc—run on the host while services that the backend depends on (Postgres, Redis) continue to run in docker containers. Would that meet the desire for a "native" development environment?

**Comment by dmarchante** [comment]
good question. I will have to pull in eyes more familiar with this. @nellshamrell @hollomancer ?

**Comment by robbkidd** [comment]
Scoping questions: Is the goal to ...

... avoid requiring a developer to install Docker?

... enable a developer to run the Ruby portions of the backend in a more direct way on their host to ease console access or running a debugger?

What challenges have developers had with docker- and cloud-based development environments that a native setup would address?

**Comment by dmarchante** [comment]
... avoid requiring a developer to install Docker?
    Potentially, we are trying to be as beginner friendly as possible. Additionally, I anticipate learners will want to know how to set up the environment locally.

... enable a developer to run the Ruby portions of the backend in a more direct way on their host to ease console access or running a debugger?

**Comment by jjhampton** [comment]
@robbkidd I suspect that your second option was one of the goals - 'enable a developer to run the Ruby portions of the backend in a more direct way on their host to ease console access or running a debugger'. I'm thinking that we want setup/running of the back-end to be something that is easy and accessible even for beginner devs. I don't have any details as I'm not very active on the back-end team here, but I've seen beginners post questions about difficulties with Docker in our Slack a few times.

It feels like we just want to give developers (especially beginners) more options instead of tying them down to only one type of environment.

**Comment by leenyburger** [comment]
@robbkidd @jjhampton @dmarchante Harry helped me set this up natively when I first got involved (a few years ago now?) and it really helps beginning developers to not have to mess with Docker. Plus byebug and Docker aren't friends. It's intimidating to run `make` commands when you're still figuring out `rake` commands. The steps are something like this: 
- Get postres running
- Modify the  / etc / hosts file: https://www.tekrevue.com/tip/edit-hosts-file-mac-os-x/
Add 127.0.0.1    operationcode-psql 
to your /etc/hosts file enables you to run Rails app that uses Docker, without Docker.
- Run redis in a different terminal window.
- You're good to go!

**Comment by wimo7083** [comment]
Looks like having a variety of options is a good choice. 
1. AWS virtual machine
2. Docker
3. Hybrid docker/ native
4. Completely native. 

I understand that docker is daunting for many people, but I feel that it adds so much easy into the process (don't have to modify hosts, don't have to install postgres) but it does add some pain.

A hybrid setup would allow easier debugging, and allow abstracting all the other things?
