### ISSUE TITLE
Create CDN to serve up codeSchool logos

### ISSUE THREAD

**Issue by kylemh** [OperationCode/operationcode_backend#28]
# Feature
## Why is this feature being added?
Currently, codeSchoolLogos are being served up by treating raw.githubusercontent.com endpoints as an API. There are rate limiters in place, and we'll likely get flagged for continuing to serve up those images in that manner.

## What should your feature do?
Hosting the images on the server while creating a CDN for them to accessed is likely the best way to handle the issue of accessing images via an API, and will be a quick CTRL+F fix in the yaml file under the `logo` attributes of each school.

**Comment by rickr** [comment]
2 questions. 

I think images belong in the frontend repo. Any objection to moving this ticket there?
Is there any reason we can't move the images to the same location the JS and HTML is being served from?

**Comment by kylemh** [comment]
We decided to pull images from source public files on the front-end.
