### ISSUE TITLE
Add Software Guild to Code Schools

### ISSUE THREAD

**Issue by ksmacleod99** [OperationCode/operationcode_backend#280]
name: The Software Guild
url: www.thesoftwareguild.com
logo: sg-logo
![37370410-7e767926-26e2-11e8-9b8e-ff76390741aa](https://user-images.githubusercontent.com/28678836/37566164-80074282-2a8b-11e8-83de-4ba1aa2d0f79.jpg)

full_time: true
hardware_included: false
has_online: true
online_only: false
locations:

va_accepted: true
address1: 252 E Market St
city: Louisville
state: KY
zip: 40202

**Comment by hpjaj** [comment]
@ksmacleod99 - Can you please supply a url for the logo.  For example, here is the one for GA:

```
"https://raw.githubusercontent.com/OperationCode/operationcode_frontend/master/src/images/codeSchoolLogos/general_assembly.jpg"
```

**Comment by ksmacleod99** [comment]
Not quite sure where to put the image to generate a URL

**Comment by hpjaj** [comment]
@kylemh - Can you pls help with the above

**Comment by hpjaj** [comment]
@ksmacleod99 - When you have a URL for the logo, can you pls drop a comment in here, and @ mention me?   I'll then add the school's info to prod.

**Comment by ksmacleod99** [comment]
https://raw.githubusercontent.com/OperationCode/operationcode_frontend/master/src/images/codeSchoolLogos/software_guild.jpg
@hpjaj  at long last!

**Comment by hpjaj** [comment]
Done!

https://operationcode.org/code_schools
