### ISSUE TITLE
General Assembly NY Duplicates on Code Schools

### ISSUE THREAD

**Issue by ksmacleod99** [OperationCode/operationcode_backend#281]
# Bug Report
## What is the current behavior?
General Assembly NY is listed three times

## What is the expected behavior?
Should be listed once

## What steps did you take to get this behavior?
https://operationcode.org/code_schools

**Comment by hpjaj** [comment]
@ksmacleod99 - General Assembly actually has three locations in New York:

```ruby
school = CodeSchool.find_by(name: 'General Assembly')

pry(main)> school.locations.where(state: 'NY').count
=> 3

pry(main)> school.locations.where(state: 'NY')
=> [#<Location:0x00000006100710
  va_accepted: true,
  address1: "10 E 21st Street (Classes)",
  address2: nil,
  city: "New York",
  state: "NY",
  zip: 10010,
 #<Location:0x00000006100530
  va_accepted: true,
  address1: "902 Broadway",
  address2: "4th Floor (HQ)",
  city: "New York",
  state: "NY",
  zip: 10010,
 #<Location:0x00000006100350
  va_accepted: true,
  address1: "35 E 21st Street (Lofts)",
  address2: nil,
  city: "New York",
  state: "NY",
  zip: 10010,
```

Although there website shows two locations in NYC:  https://generalassemb.ly/locations/new-york-city

Can you pls confirm with them if the third location is valid, or should be deleted?

**Comment by ksmacleod99** [comment]
Sure! I can reach out. Also, is there a way to make them look different? I guess that's a front-end issue, isn't it?

**Comment by kylemh** [comment]
https://github.com/OperationCode/operationcode_frontend/issues/934
