### ISSUE TITLE
Point to AWS API for Code Schools image src's

### ISSUE THREAD

**Issue by kylemh** [OperationCode/operationcode_backend#284]
# Feature
## Why is this feature being added?

We're moving off of GitHub's assets src as an API.

## What should your feature do?
I'm not sure where the data is grabbed from anymore, but the model for code_schools includes a `logo` key. The fields should be adjusted to the format of this example url: `https://s3.amazonaws.com/operationcode-assets/codeSchoolLogos/bloc.jpg`

## Existing Data

[Here is a sorted list](https://gist.github.com/hpjaj/ef81f7409f8daff7b563a2e874693f14) of the `CodeSchool` db records in production as of March 27th.  Namely their `name` and `url` attributes:

https://gist.github.com/hpjaj/ef81f7409f8daff7b563a2e874693f14

## Definition of done

- [ ] A rake task that updates all of the `CodeSchool` records' `url` attributes accordingly
- [ ] Smoke test that the updates are working, by [running the front and backends together](https://github.com/OperationCode/operationcode_backend/wiki/Running-The-Front-and-Backend-Repos-Together) in your local dev env

**Comment by jvillama** [comment]
Hi @kylemh, I can take this. Would this involve just updating the `code_schools.yml` file to the correct AWS url endpoints?

**Comment by hpjaj** [comment]
@jvillama - It's yours!  I have updated the issue's description with resources and acceptance criteria.  Ping me if you run into any blockers.

**Comment by jvillama** [comment]
@hpjaj The rake task is supposed update all of the `CodeSchool` records' `logo` attributes correct?
