### ISSUE TITLE
Create FAQ endpoint

### ISSUE THREAD

**Issue by rickr** [OperationCode/operationcode_backend#3]
This endpoint should take a YAML config file and return a json response.

Use [this file](https://github.com/OperationCode/operationcode/blob/master/config/faqs.yml) as the source.

I'd like to see this moved back to the front end eventually.

**Comment by leenyburger** [comment]
Is this thought process correct?
1.  Add the YML file to config folder
2. Create faq.rb class in lib folder.  Load the yml file in the initialize method. 
3. Create an faq_controller in the v1 folder.  In the index method create the faq object and render json.
4. Create the "get" route in the routes file.  api/vi/faq

**Comment by leenyburger** [comment]
I'd like to take this one if about comments look good.

**Comment by rickr** [comment]
We've taken a different direction and are now storing our FAQs in a gitbook. That's being tracked in operationcode/documents#3 so I'm going to close this out.
