### ISSUE TITLE
Swap existing Pundit implementation for CanCanCan

### ISSUE THREAD

**Issue by hpjaj** [OperationCode/operationcode_backend#301]
# Feature
## Why is this feature being added?

Pundit is only used in one place in our app.  CanCanCan works with ActiveAdmin, and supports a tiered permissions approach.

## What should your feature do?

- [ ] Find where Pundit is used and swap it out for CanCanCan
- [ ] Remove Pundit from the app

**Comment by nagano564** [comment]
Too early to start another one?

**Comment by hpjaj** [comment]
Yes

**Comment by nagano564** [comment]
@hpjaj is this available to take over?

**Comment by hpjaj** [comment]
@nagano564 - It's yours!  Ping me if you have any questions on it.
