### ISSUE TITLE
Slack Integration 4: Rake task to add slack usernames based on email

### ISSUE THREAD

**Issue by wimo7083** [OperationCode/operationcode_backend#312]
# Feature
## Why is this feature being added?
Most of our community happens in the Slack workspace; slack uses `id` as the primary key. Non-slack data and user information is stored with `email` as unique key and with a unique PK. 

Being able to connect the FE, BE and slack information is pretty important. It's desired to use the Slack API to join the two bits of information. 

## What should your feature do?
Run a rake task to get the slack username from the slack API.

Modifying this after some direction from @hpjaj.

This task will leverage the existing capabilities of pybot and limit the number of application tokens to the oc.org slack workspace with `users:read` and `users:read.email` scopes.

1. Maintainer triggers this rake task
2. Request is sent to pybot to get a determined amount of users from the `users.list` endpoint
a. might make this less by passing emails to slackbot
b. might ask for all users
c. might use pagination and get a certain amount at a time.
3. Pybot does whatever it needs to get some users
4. Events are received at the to be built `SlackUser:create` or `SlackUser:update`

**Comment by hpjaj** [comment]
Dependency: https://github.com/OperationCode/operationcode_backend/issues/318

**Comment by wimo7083** [comment]
Closed due to changing of design.
