### ISSUE TITLE
Slack Integration 1: Create New DB Table

### ISSUE THREAD

**Issue by wimo7083** [OperationCode/operationcode_backend#318]
# Feature
## Why is this feature being added?
This feature is being added so that identifying information from the Slack API can be stored in the production database. 

By adding a new DB we will reduce the bloat of `User` and allow new contributors to practice performing joins on the DB instance. 

## What should your feature do?
- [x]  create new db table `SlackUser` table
- [x]  remove `User:slack_name` 
- [x]  create migration to perform both actions.

---
## SlackUser Table
| key | attribute |  example |
| ---   | --- | --- |
| FK, unique | user_id  |   20 |
|   unique   | slack_id     | "W012A3CDE"| 
|      |  slack_name    |  "harry" | 
|      | slack_real_name     | "William Michael John" |
|      | slack_display_name     |  "Very Unoriginal" | 
|  unique    | slack_email  | "thebestwrestler@wwf.com" |

**Comment by wimo7083** [comment]
I'd like to work on this first.

**Comment by hpjaj** [comment]
@wimo7083 - It's yours!  Let me know if you need a hand with anything.

**Comment by hpjaj** [comment]
When a new db table is created, you will also want to create a new SlackUser model.  This is where the business logic will reside for validations, associations, etc.

**Comment by wimo7083** [comment]
Looking at the other models I'm getting an idea of what these do. These look like the private classes that manipulate the database directly that you can expose to the endpoint handlers. Since any email changes are coming from slack I probably don't need email validation. But I could put the query in here to perform the join to find user.

Other than that not sure what custom methods I should include.

**Comment by hpjaj** [comment]
@wimo7083 - How goes on the code review comments?  Any questions?

**Comment by hpjaj** [comment]
@wimo7083 - We need to get this issue closed in the next few days, as it is blocking the 5 remaining Slack issues.  

I can take the issue over if you don't have the bandwidth.  Pls let me know ASAP.

**Comment by hpjaj** [comment]
completed in https://github.com/OperationCode/operationcode_backend/pull/324
