### ISSUE TITLE
Slack Integration 2: Add SlackUser Service Class

### ISSUE THREAD

**Issue by wimo7083** [OperationCode/operationcode_backend#319]
# Feature
## Why is this feature being added?
Feature is being added to perform the actions required to manage modification of the `SlackUser` table.

## What should your feature do?

Class will have two modification methods:
1. create
2. update

## Create Actions
1. Method uses provided email to query for `User`
2. User is found:
a. Creates a new `SlackUser` on FK `email`
b. Sends 201.
3. User is not found:
b. Creates a new `SlackUser` on FK `email` with no match of FK.
c. Sends 201
d. sends new `POST` to controlling endpoint for slack telling to send email update request.

## Exisiting User updates
1. Method uses provided email to query for `User`
2. User is found:
a. Updates `SlackUser: email`
b. Sends 201.
3. User is not found:
b. Creates a new `SlackUser` on FK `email` with no match of FK.
c. Sends 201
d. sends new `POST` to controlling endpoint for slack telling to send email update request.

Putting the `POST` in a separate action verify of reciept.
201 Response for both actions because the row is modified even if it has no FK match.

**Comment by hpjaj** [comment]
Dependency: https://github.com/OperationCode/operationcode_backend/issues/318

**Comment by hpjaj** [comment]
@wimo7083 - For the case where the user is not found in our db, we need to send them a Slack message.

Is there a PyBot endpoint that we can `POST` to to trigger a private message to a user?

If yes, can you provide all the details (URL, params, headers, etc.), including any auth requirements.

**Comment by jdollar** [comment]
Hey @wimo7083 is it cool to pick up this issue?

Had a couple questions based on the original description:

- Is there an example of a service class in the current codebase? Is it just a controller out there or are there specific service classes?
- For the "failed for find user" scenarios, what are the controlling endpoints? Are you guys just looking for the action to call out to the slack api to send a email to the user?
- Can you elaborate on the "Putting the POST in a separate action verify of reciept." line item?

**Comment by wimo7083** [comment]
Here's the origial https://github.com/OperationCode/operationcode_backend/issues/314

1. Service class: here's where all the current controllers for endpoints are:
https://github.com/OperationCode/operationcode_backend/tree/master/app/controllers/api/v1
Essentially we'd be getting some HTTP event from another web service that is telling us to create or add a slack user account with that slack user information and relating it to the email stored in `users` 
2.  An example of a failed to find user: user signed up with our website, and somehow signed up with a different email. This is very unlikely but can occur if an admin sends a request without requiring a website account.  This lack of user will come from not being found in our `users` table.
3.  I'm unsure about this item. Possibly we need to send a response to the sending requst that we got the message and we did some action? (correctly updated or correctly created).

**Comment by wimo7083** [comment]
Assigning to myself as placeholder.

**Comment by jdollar** [comment]
Tossed a pull request and left some comments on a couple items for your review!

**Comment by wimo7083** [comment]
Closed due to changing of design.
