### ISSUE TITLE
Uninstall Forest Admin

### ISSUE THREAD

**Issue by hpjaj** [OperationCode/operationcode_backend#323]
# Feature
## Why is this feature being added?

This PR added Forest admin: https://github.com/OperationCode/operationcode_backend/pull/283

It needs to be uninstalled, as we are using ActiveAdmin instead.  Here are the instructions to uninstall forestadmin:

https://doc.forestadmin.com/knowledge-base.html#uninstall
## What should your feature do?

- [ ] Clean uninstall of ForestAdmin and everything from https://github.com/OperationCode/operationcode_backend/pull/283

**Comment by kirbygit** [comment]
can I do this? This is in regards to gem 'forest_liana' right?

**Comment by kirbygit** [comment]
issue in progress in pr #327
