### ISSUE TITLE
Use standardized format

### ISSUE THREAD

**Issue by wimo7083** [OperationCode/operationcode_backend#326]
# Feature
## Why is this feature being added?
Start working towards a standardized formatter/ linter such as the FE does. 

Options I've seen include rubocop and rufo. I've started using rufo locally and while it's great in some cases it I can't get single_quotes setting to work. 

## What should your feature do?
Include a formatter config setting and documentation on how to setup the linter so that it correctly works with minimal contributor action.

**Comment by hpjaj** [comment]
Let's use rubocop, it is more of an industry standard.

**Comment by kirbygit** [comment]
I'll work on this

**Comment by nagano564** [comment]
Are you working on this @kirbygit. If not I would like to give it a go

**Comment by kirbygit** [comment]
All yours
