### ISSUE TITLE
Add `rep_name` and `rep_email` to CodeSchool

### ISSUE THREAD

**Issue by hpjaj** [OperationCode/operationcode_backend#332]
# Feature
## Why is this feature being added?

The frontend would like to start gathering contact information for a code school.

## What should your feature do?

- [ ] Add `rep_name` (string) to the `CodeSchool` table
- [ ] Add `rep_email` (string) to the `CodeSchool` table
- [ ] Add attrs to serializer
- [ ] Add attrs to strong params
- [ ] Update apiary docs
- [ ] Add spec illustrating presence
- [ ] Add attrs to factory
- [ ] Add attrs to associated active admin resource

**Comment by nagano564** [comment]
Can I start this?
