### ISSUE TITLE
Add Firehose Project to Code Schools section

### ISSUE THREAD

**Issue by kirbygit** [OperationCode/operationcode_backend#341]
# Feature
## Why is this feature being added?

Firehose Project is in the process of a possible partnership offering a scholarship to eligible veterans in the Los Angeles Area. For now add them to the Code Schools section -> Online Schools
## What should your feature do?
Add the Logo attached to this issue
1. The logo is attached for Firehose Project
2. Currently not accepting the G.I. bill
3. Location: San Francisco, CA
4. url: https://thefirehoseproject.com/
5. email: questions@thefirehoseproject.com
6. hardware included: false
---

<img width="170" alt="logomark" src="https://user-images.githubusercontent.com/20747057/39595602-df93027e-4ec4-11e8-8f87-82abeb12d594.png">

**Comment by jjhampton** [comment]
@kirbygit We can add it via the Admin Dashboard's GUI now, which I would venture to say falls into "back-end", but shouldn't require any back-end code changes or pull-requests to be merged in.

So you can probably leave it open here, just make sure that whoever will be adding it has:
*  the base logo (what you posted above will work)
* the ability to edit the logo / upload to S3 (@kylemh or I can do this currently, not sure about any others)
* any other required info, see the data shape in https://github.com/OperationCode/operationcode_backend/blob/master/config/code_schools.yml for examples

**Comment by kirbygit** [comment]
ok will reeopen this thanks @jjhampton

**Comment by jjhampton** [comment]
If this is a 'Partner School', those are currently hardcoded in the front-end React project - but until then, a normal Code School managed by Admin will work. Looks like we need a few more details for the info, too.

**Comment by kirbygit** [comment]
Partner School is currently in talks. A normal Code School is fine for now

**Comment by jjhampton** [comment]
Added via Admin Dashboard.
