### ISSUE TITLE
Add Service resource to admin dashboard

### ISSUE THREAD

**Issue by hpjaj** [OperationCode/operationcode_backend#342]
# Feature
## Why is this feature being added?

Gives admins the ability to conduct CRUD actions on the `Service` model.  Currently this has to be done through prod's rails console.

## What should your feature do?
Here are the ActiveAdmin docs:  https://activeadmin.info/documentation.html

Here is a sample implementation of a Resource in our codebase:  https://github.com/OperationCode/operationcode_backend/blob/master/app/admin/team_member.rb

- [ ] Adds a Resource for `Service` to ActiveAdmin
- [ ] Updates `ability.rb` with the proper permissions - confirm with @hpjaj

**Comment by nagano564** [comment]
What permissions do you want to give admins over the `service` model? All CRUD actions? 

How can I check this if I don't have access to the ActiveAdmin dashboard?

**Comment by hpjaj** [comment]
1. Let's follow the same pattern as is done for [TeamMember](https://github.com/OperationCode/operationcode_backend/blob/master/app/models/ability.rb)
2. You'll need to create three `AdminUser`s.  One with each role: super admin, admin, and board member.  And then login and out as each, testing access.  This is all done in your local test env (i.e. localhost).

**Comment by nagano564** [comment]
should I create something like so?

https://github.com/OperationCode/operationcode_backend/blob/53377ae3418a6d9735d69e4cd63efa7182885499/test/models/team_member_test.rb

**Comment by hpjaj** [comment]
So `AdminUser` is just another db table.  And it has a `belongs_to` relationship with `Role`:

https://github.com/OperationCode/operationcode_backend/blob/master/app/models/admin_user.rb#L7

So you'll just be creating the [three defacto role records](https://github.com/OperationCode/operationcode_backend/blob/master/lib/tasks/roles.rake#L4) in your local db, and then creating three new `AdminUser`s, and associating each one with each role.

The seeds file creates one `AdminUser` for you:

https://github.com/OperationCode/operationcode_backend/blob/master/db/seeds.rb#L35

To conduct testing, you'll go to http://localhost:3000/admin/login
