### ISSUE TITLE
Adds new resources to ActiveAdmin for `Scholarship` and `ScholarshipApplication`

### ISSUE THREAD

**Issue by hpjaj** [OperationCode/operationcode_backend#349]
# Feature
## Why is this feature being added?

Gives admins the ability to conduct CRUD actions on the `Scholarship` and `ScholarshipApplication` models.  Currently this has to be done through prod's rails console.

## What should your feature do?
Here are the ActiveAdmin docs:  https://activeadmin.info/documentation.html

Here is a sample implementation of a Resource in our codebase:  https://github.com/OperationCode/operationcode_backend/blob/master/app/admin/team_member.rb

- [ ] Adds a Resource for `Scholarship` to ActiveAdmin
- [ ] Adds a Resource for `ScholarshipApplication` to ActiveAdmin
- [ ] Updates `ability.rb` with the proper permissions - confirm with @hpjaj 
- [ ] These two models have a `has_many/belongs_to` relationship with one another.  Be sure to take that into account.  We have an existing implementation for `CodeSchool` and `Location` that can be used for reference.
- [ ] Create three `AdminUser`s. One with each role: super admin, admin, and board member. And then login and out as each, testing access. This is all done in your local test env (i.e. localhost). The `seeds` file can help with this.

**Comment by nagano564** [comment]
Can I do this?

**Comment by hpjaj** [comment]
@nagano564 - It's yours!
