### ISSUE TITLE
Manual data update in code_schools.yaml

### ISSUE THREAD

**Issue by kylemh** [OperationCode/operationcode_backend#36]
# Improvement
## Why is this improvement being suggested?
I noticed that Galvanize is missing some locations, there may be other code schools with new locations or other out-of-date details.

## What would your improvement do?
By updating `code_schools.yaml` with up-to-date information, we can ensure that our audience is receiving correct information.

------------------

**If you are looking for Open Source contribution - this is easy pickings! 
See comments for a very thorough walk-thru.**

**Comment by lennonc** [comment]
I'm a first time contributor and I'd like to grab this. What's the protocol for that?

**Comment by kylemh** [comment]
@lennonc 

Firstly, thank you for wanting to pick up this task!

You can start by examining the current `code_schools.yaml` file under `config/` at the top level of the repository ([located here](https://github.com/OperationCode/operationcode_backend/blob/master/config/code_schools.yml)).

Instructions for relevant data is commented within the first few lines of `code_schools.yaml`

### Instructions
1. In your command line interface (CLI), go to the file path in which you'd like to put this repository (Desktop for example).
2. Use `git clone https://github.com/OperationCode/operationcode_backend.git` in your CLI.
3. Use `git checkout -b update-code-schools-data` to create and checkout a new branch.
3. Go into the repository, go into `config/`, and open `code_schools.yaml` with your favorite text editor.
4. You should comb the file's current data, check out the school's website, and verify the data through any means necessary (Google Maps, Google Search, and/or calling the Code School). 
5. If there is a discrepancy (out-of-date information on `code_schools.yaml`), make an edit locally.
6. Once you've finished combing the entire file and made all of your fixes, use the following commands on your repository:
    - `git add *`
    - `git commit -m "resolve #36"`
    - `git push -u origin update-code-schools-data`
7. Come back to GitHub and create a Pull Request 💃 

**Some standards to remember:**
- For address, please use abbreviated cardinal directions (SW, NE, W, etc.)
- For address, please use unabbreviated road types (road, not Rd. & street, not St.)

**Comment by hpjaj** [comment]
@kylemh - I'm thinking here we'd want to:

- create a new `CodeSchool` db table
- [CRUD](https://en.wikipedia.org/wiki/Create,_read,_update_and_delete) API endpoints for `CodeSchool` records 
- `rake` task that creates a `CodeSchool` record for each entry in `code_schools.yml` 
- wiring up the existing `:index` endpoint to fetch `CodeSchool` db records
- test coverage for new endpoints
- update our [API documentation](https://github.com/OperationCode/operationcode_backend/blob/master/apiary.apib)

Si?

**Comment by kylemh** [comment]
This is blocked by #99 #106 and #107

**Comment by benJervis** [comment]
Hi @kylemh, is this issue still available? I'm a first time contributor, and was hoping I could tackle this one for Hacktoberfest.

**Comment by kylemh** [comment]
@benJervis Please feel free! It's simple busy work. You'll just scour the websites currently in that yaml file, and make sure the info is up-to-date. I'd also appreciate you adding an email field to every school because that will help us with https://github.com/OperationCode/operationcode_frontend/issues/364

Be wary @hpjaj that I'm asking for a model change!

**Comment by benJervis** [comment]
@kylemh, I'm all done and trying to create a PR, following your instructions in that comment from June, but I don't have permission to push to the remote. Should I have forked it instead?

**Comment by kylemh** [comment]
@benJervis looks like you figured it out. The answer is yes. 

I'm very sorry for those incorrect instructions. Back when I made them this repo was organizers only, and as members of OC we have the ability to clone and make PRs from our own clones.
