### ISSUE TITLE
Alert community leaders when a new member joins in their area

### ISSUE THREAD

**Issue by rickr** [OperationCode/operationcode_backend#37]
# Feature
## Why is this feature being added?

Community leaders have already become a vital part of Operation Code. They provide local support, connections and a friendly face near to our users. We should make it easier for our community leaders to know when a new member joins in their area.

## What should your feature do?
When a member joins check to see if there's a community leader within a certain range of the new user. If there is send the community leader a message notifying of the new user.

**Comment by DRBragg** [comment]
just a simple action mailer? or something with slack integration?

**Comment by hollomancer** [comment]
Let's start with an action mailer - Slack can come later.

**Comment by DRBragg** [comment]
Sounds good, I can take this on

**Comment by DRBragg** [comment]
to clarify, where are the community leaders emails stored?

**Comment by hollomancer** [comment]
Right now it's not in the database. @hpjaj, this may be a situation where we want to be able to tag that a user is a community leader...

**Comment by DRBragg** [comment]
that's what I was looking at, I wasn't sure if volunteer boolean was used for community leader, or if that needs to be added to the schema?

or add emails to the team_memebers.yml and the a column to team_members, if they are the same.

**Comment by hpjaj** [comment]
@hollomancer - We can leverage [ActsAsTaggagleOn](https://github.com/mbleigh/acts-as-taggable-on) for this.  We already have a [sample implementation](https://github.com/OperationCode/operationcode_backend/blob/master/app/models/resource.rb) for it on the `Resource` model.

We could [add it](https://github.com/mbleigh/acts-as-taggable-on#usage) to the `User` model, as well, and add tag(s) to `User`s.  And then [query for](https://github.com/mbleigh/acts-as-taggable-on#finding-tagged-objects) `User`s with the given tag(s).

**Comment by Hiren-Mehta** [comment]
Here is the relevant high-level issue where the requirements are discussed: https://github.com/OperationCode/operationcode/issues/749

**Comment by hpjaj** [comment]
@hollomancer @jjhampton @kylemh - How do we define a "community leader"?

How would you envision the UI experience for a `User` getting tagged as a community leader?

Would this be: 

1. a page in the OC UI that only users with permissions can access, to tag a user as a community leader?
2. clicking a "community leader" button in the new admin panel/dashboard on the user's show page?
3. any user can designate themselves as a community leader in the OC UI?
4. ?

**Comment by hollomancer** [comment]
Given the limited number of people to do this, #2.

**Comment by hpjaj** [comment]
👍  I'll build that feature into https://github.com/OperationCode/operationcode_backend/pull/181

**Comment by hpjaj** [comment]
@DRBragg - I'll add in the tagging functionality in the above PR. As such, you can assume that you will be able to find eligible user's by querying `User.tagged_with("community leader")`.

Are you still interested in taking on this issue?

**Comment by DRBragg** [comment]
Tracking.

I'm happy to continue to working on this.

**Comment by hpjaj** [comment]
@DRBragg - It's yours!  Marking it as **In Progress**.  Don't hesitate to reach out if the need arises.

**Comment by DRBragg** [comment]
Unfortunately I'm having a hell of a time getting Docker to run on my machine.  This is certainly a project I feel comfortable tackling but I don't want to delay it or cause someone to miss an opportunity here.  I'm going to continue to try to get Docker running and hopefully work on this but it might be something you want to change back to `Status: Available`.

**Comment by DRBragg** [comment]
@goodcleanfun can definitely handle this issue so we're good

**Comment by hpjaj** [comment]
@DRBragg - How goes?  Any questions we can answer on this?

**Comment by DRBragg** [comment]
I passed this off to another dev, @goodcleanfun.  I dont have a way of running Docker on my machine but he should be able to handle it.  I will follow up with him this weekend and see where he is at.

**Comment by hpjaj** [comment]
@DRBragg - Thanks

**Comment by hpjaj** [comment]
@DRBragg @goodcleanfun - As there has not been a pull request, or any recent activity on this issue, we are assuming it has become abandoned.  We are marking it available for other members to contribute.

Here are [our contributing guidelines](https://github.com/OperationCode/operationcode/blob/master/CONTRIBUTING.md#guidelines-for-working-an-issue) which discuss the process and **timelines** for working an issue.  You are more than welcome to re-reserve the issue, if it remains marked as "Status: Available"!

**Comment by hpjaj** [comment]
Per [discussion above](https://github.com/OperationCode/operationcode_backend/issues/37#issuecomment-336679107), this is how we will be defining a community leader:

> clicking a "community leader" button in the new admin panel/dashboard on the user's show page

This depends on https://github.com/OperationCode/operationcode_backend/pull/183 , which is currently blocked for infrastructure related reasons.  

As such, marking this as blocked until that PR is un-blocked.

**Comment by nagano564** [comment]
K.. let's see if I can figure this out

**Comment by hpjaj** [comment]
@nagano564 - It's yours!
