### ISSUE TITLE
Populate Airtable with mentee's email address as part of mentor request

### ISSUE THREAD

**Issue by jjhampton** [OperationCode/operationcode_backend#377]
# Feature
## Why is this feature being added?

Follow on to #259 
## What should your feature do?
Part of requesting a mentor currently (via the Airtable UI) involves the mentee submitting their email address as one of the required requst fields. This serves as a way for a mentor to contact the mentee in the event that they are not yet on Slack. In the past, there have been multiple mentees who were unfamiliar with Slack and had entered incorrect data in the 'Slack name' field, and an email address served as a default fallback for communication.

Looks like #259 left the email address out of the initial requirements. We'll need to add that as part of the React form -> Rails app -> Airtable mentor request process that's still in progress.

**Comment by jjhampton** [comment]
I can work on adding this in as I continue to (slowly) work on front-end issue https://github.com/OperationCode/operationcode_frontend/issues/971 .

**Comment by wimo7083** [comment]
We were hoping to do this by integrating with be. The ultimate goal was to use the information from the frontend login to propulate slack name, email, etc. Be connecting BE  and pybot and use pybot to manage the user changing their slack email and name to update the stored data in BE.

**Comment by jjhampton** [comment]
@wimo7083 Is that idea set up yet, or are there plans for it? Currently what's happening when I send a Mentor Requests from the Backend to Airtable is that it's the only data sent is: 
```
:slack_user,
:services,
:skillsets,
 :additional_details,
 :mentor_requested
```
And the email field is left blank on Airtable after the request is populated.

**Comment by wimo7083** [comment]
No there are issues for it, the next steps are writing up the controllers.
