### ISSUE TITLE
Clicking change password doesn't actually work.

### ISSUE THREAD

**Issue by AshTemp** [OperationCode/operationcode_backend#379]
# Bug Report
## What is the current behavior?
When clicking change password user is told we are unable to set the password for this email.

## What is the expected behavior?
The password resets.

## What steps did you take to get this behavior?
1. Open www.operationcode.org.
2. Click login.
3. Click forgot password.
4. Go to email and click link in email to change password.
5. Attempt to change password.

### Operating System
Windows 10
### Browser
Chrome 

### Screenshots
![image](https://user-images.githubusercontent.com/19790104/43647670-5dfb50d8-9706-11e8-8513-ff9106a9a0c3.png)

**Comment by wimo7083** [comment]
I just tried to do it and it works for me. For some reason we thought it had to do with the FE sending a `PATCH` and the BE expecting a `POST` 

I just tried this and it's working in chrome to send a PATCH. 

```
Request URL: https://api.operationcode.org//users/password
Request Method: PATCH
Status Code: 200 
Remote Address: 18.218.241.113:443
Referrer Policy: no-referrer-when-downgrade```

I don't see how this patch could be getting to the right controller since we don't have any PATCH setup for that route.

**Comment by AshTemp** [comment]
It's still broken for me? New logs are in the channel.

**Comment by AshTemp** [comment]
After further testing with Will, the user can click the password recent link from a previous email and it will work. Initially clicking the reset link on the most recent email will result in failure. However, after the user is successfully able to change the password with a previous link the most recent link will also work.

**Comment by robbkidd** [comment]
A little more information: the first password reset attempt that shows an error appears to actually succeed in changing the user's password despite the display of the error.

**Comment by jjhampton** [comment]
Originally I thought the front-end might have been mishandling the response and causing some type of  redirect loop, but I don't think so anymore.  

I think the usage of PATCH in the back-end has to be related here - I can't reproduce this consistently every time, but in local dev, after submitting the password reset form, the back-end resets the password, responds with a 302 message, but then also responds with a 404 error, which is causes the front-end Promise to reject and enter the catch clause on setPassword.js, line 48 (which displays the error message).

I'm seeing `ActionController::RoutingError (No route matches [PATCH] "/")` in the back-end terminal after I reset the password, and in the front-end DevTools Network tab, the browser is receiving the matching error response (which causes the catch clause in setPassword.js, line 48 to fire and the error message to displayd): 

```
error: "Not Found"
exception: "#<ActionController::RoutingError: No route matches [PATCH] "/">"
status: 404
```

**Comment by robbkidd** [comment]
Discovered this morning that a second send-me-a-reset-email is not necessary. Only need to click the "Set Password" button again after seeing the error to get the success and redirect to `/login`.

**Comment by desnudopenguino** [comment]
Beyond being an annoyance, this could be a security issue if someone's email is compromised and an old password reset email is available. My initial thoughts are to correct whatever issue is preventing the newest reset link from working, setting an expiration on the link so that after x time, it won't work anymore, and setting older reset links as invalid once a new one is requested. I don't see this being too complex of a fix, but I haven't actually looked at the code yet, but I'd love to tackle the problem.

**Comment by robbkidd** [comment]
> […] correct whatever issue is preventing the newest reset link from working, setting an expiration on the link so that after x time, it won't work anymore

I agree with these.

> setting older reset links as invalid once a new one is requested

This seems good, but I wonder about the consequences.

**Comment by AshTemp** [comment]
So this works for now, but we still need to eventually fix the
underlying issue of the link not working the first time someone clicks it.

**Comment by wimo7083** [comment]
Looks like we try to be configured to 6 hours.

https://github.com/OperationCode/operationcode_backend/blob/5df843a43619738df7900969b59c6edb009966bd/config/initializers/devise.rb#L206


https://secure-web.cisco.com/REALLY_LONG_UNIQUE_STRING_UNSURE_IFAUTH/https%3A%2F%2Foperationcode.org%2Freset_password%3Freset_password_token%$Some_token

For acceptance criteria:
1. Create documentation to understand password reset process.
2. Prevent errors from being sent to FE if the reset process is valid .
3. Expire links after $TIME_PERIOD.
4. Prevent multiple current-active requests for a single user. 

Do these seem reasonable?

**Comment by wimo7083** [comment]
Placholder assigning for @desnudopenguino.

**Comment by desnudopenguino** [comment]
@wimo7083 What sort of documentation do you want? Technical back-end processing, or documentation for the end user for the process (or both?). What is the FE?

@robbkidd Are you on board for criterion 4 above? I've seen many sites with the same functionality. The goal is to allow one point of entry at a time for a user to reset their password. The worst consequence would be if the email message was a bit slow and the user requested a 2nd password reset. In that case they'd have to wait for the 2nd email.

**Comment by wimo7083** [comment]
FE = frontend, which is our react repo sending requests for the password change. 


After you figure out how this all works, I want to be able to have something that if you were to lose internet for a month I'd want to be able to tell:
1. What is sending the emails
2. What is required for a valid password request
3. How long is a password request valid for
4. How can password requests get cancelled
5. If there's anything you find that's odd that you recommend we leave in that would have us scratching our head later that would be awesome to know about. 

If you find it valuable you could include a process diagram. Basically the whole point is to get the knowledge somewhere so later we know what is going on.

**Comment by desnudopenguino** [comment]
Gotcha. Do we have a documentation location where I post that info, or should I include it here (at least initially)? I should be able to start investigating later today or tomorrow.

**Comment by wimo7083** [comment]
I think something in here: https://github.com/OperationCode/operationcode_backend/tree/master/docs would be good. 

If you can structure the code in a way that you don't need too much documentation that might be better. I don't want stale comments misleading people. But a problem we face is lots of new programmers contributing and needing _additional_ documentation.

**Comment by robbkidd** [comment]
From @jjhampton's [comment](https://github.com/OperationCode/operationcode_backend/issues/379#issuecomment-414896045):
> Locally, when I change the front-end API call to /users/password from a PATCH to a POST, I no longer get the 404 error response on the back-end anymore (in the Devise redirect after resetting password), and the FE Promise is resolving successfully, with no error message displayed, and the user is successfully redirected in the React app to the /login route, as intended.

I suggest we go with this. (Change from PATCH to POST in the frontend form for the reset.) If that's not the wholly correct thing to do, it would fix password resets while the correct thing is researched.

**Comment by kylemh** [comment]
@robbkidd this was already done: https://github.com/OperationCode/operationcode_frontend/blob/master/src/scenes/home/resetPassword/setPassword/setPassword.js#L37

Perhaps that's the reason it broke?

**Comment by robbkidd** [comment]
Well, color me confused. 😕 OK.

**Comment by jjhampton** [comment]
@kylemh When this bug was originally reposted, we were calling PATCH with `axios.patch(`${config.backendHost}/users/password` from the Front-End:

https://github.com/OperationCode/operationcode_frontend/blob/a86f412a71ba05e5dc3a843ad59676637eda64ce/src/scenes/home/resetPassword/setPassword/setPassword.js#L38

Now we're calling POST: `axios.post(`${config.apiUrl}/users/password`

So not only was the REST verb changed, but also the config variable being used to create the API URL string.

We're gonna have to debug this one to figure out what's going on.

**Comment by kylemh** [comment]
```
After further testing with Will, the user can click the password recent link from a previous email and it will work. Initially clicking the reset link on the most recent email will result in failure. However, after the user is successfully able to change the password with a previous link the most recent link will also work.
```

It worked before, the problem was the error message was a lying sack of shit.

**Comment by wimo7083** [comment]
Yeah, looks like the previous way used the base url 

https://github.com/OperationCode/operationcode_frontend/pull/1043/files#diff-9942e3d024e08e7cc7abc2b47efb89f7L1

which is defined here:
**https://github.com/OperationCode/operationcode_frontend/pull/1043/files#diff-9942e3d024e08e7cc7abc2b47efb89f7L1**

I think these are the default values for the resource = `users`
https://github.com/OperationCode/operationcode_backend/blob/5df843a43619738df7900969b59c6edb009966bd/app/controllers/users/passwords_controller.rb

**Comment by wimo7083** [comment]
Yeah I think previously we got an error because rails routed the PATCH to the correct location, and maybe FE was expecting something else?

**Comment by jjhampton** [comment]
The false error message appeared to have something to do with how Rails & Devise was trying to redirect after the password reset successfully occurred (status 302 and 404)

If it's completely broken now, then that seems another issue altogether.

**Comment by robbkidd** [comment]
Definitely want to POST to the base URL, not the API URL. `api/v1` is not part of the backend's URL path to the password update endpoint.

```
> be rake routes | grep password | grep update
admin_user_password PATCH  /admin/password(.:format)     active_admin/devise/passwords#update
                    PUT    /admin/password(.:format)     active_admin/devise/passwords#update
      user_password PATCH  /users/password(.:format)     devise/passwords#update
                    PUT    /users/password(.:format)     devise/passwords#update
```

**Comment by kylemh** [comment]
@robbkidd can we make it so that it is? It's weird to need 2 back-end URLs. 

Every request should resolve at one host, and I was under the impression it would end with `/v1`

**Comment by wimo7083** [comment]
Because this isn't part of our official api, the only api event right now is password#reset which requests the email. 

It's the same reason the admin dashboard isn't under `api/v1`

Yes eventually It'd be nice to have this done correctly, but I'm not sure how.
