### ISSUE TITLE
Create ID.me verification endpoint

### ISSUE THREAD

**Issue by rickr** [OperationCode/operationcode_backend#38]
# Feature
## Why is this feature being added?

We need to support verifying users via ID.me

## What should your feature do?
Create an endpoint `/api/v1/users/profile/verify`
You will be passed one parameter `access_token`.
Take that parameter and GET the following URL to `https://api.id.me/api/public/v2/attributes.json ?access_token=ACCESS_TOKEN`
That should provide you with the following payload:
```
{
  "id": "a1b2c3d4e5f6g7h8i9j0",
  "verified": true,
  "affiliation": "Service Member",
  "fname": Test,
  "lname": User,
  "email": "test.user@id.me",
  "uuid": "a1b2c3d4e5f6g7h8i9j0"
}
```
The data from `verified` should be stored as an attribute on the `User` determined via the JWT

**Comment by hpjaj** [comment]
@rickr - I can take this one.

**Comment by hollomancer** [comment]
All yours @hpjaj!

**Comment by hpjaj** [comment]
@rickr - In the workflow laid out in this PR's description it says that the payload returned from id.me looks like this

```
{
  "id": "a1b2c3d4e5f6g7h8i9j0",
  "verified": true,
  "affiliation": "Service Member",
  "fname": Test,
  "lname": User,
  "email": "test.user@id.me",
  "uuid": "a1b2c3d4e5f6g7h8i9j0"
}
```
and
> The data from `verified` should be stored as an attribute on the `User` determined via the JWT

As such, we would be:

1. Creating a `boolean` attribute on `User` of `verified`
2. Setting this user's `verified` attribute to `true` if verified

Our db `user_id` is not provided in this payload, nor in the original request to the new endpoint.  **Where is the `user_id` coming from?**

id.me sends back first and last name, and email.  I assume we are _not_ doing a fuzzy search on this info to find and/or create a `User`?

I was looking through the frontend issues, and it looks like [this issue](https://github.com/OperationCode/operationcode_frontend/issues/118) is where the user clicks the new "verify" button.  Meaning we would have a `user_id` **prior** to the verify button being clicked.

If that is the case, should we assume that when the new  `/api/v1/users/profile/verify` endpoint is hit, it will not only include the `access_token` parameter, but also the `user_id` parameter?

Or perhaps is there something nestled in the JWT that we can unpack the `user_id` from?  

If not, can you please elaborate on how the backend will narrow down the user in question.

**Comment by rickr** [comment]
Hey Harry - great question. Sorry it isn't clarified a little bit more in the original ticket. This verification process does require a user to be signed up and signed in.

The JWT auth stuff should be all wired up with devise so you should be able to use the standard `current_user` devise tricks. 

If not this is the gist of what's happening. The JWT being passed back to the API server on every request. The JWT has data in it and using that data we can get the current user. 

Here's an example of a login:
```
http POST localhost:4000/api/v1/sessions user:='{"email": "test@example.com", "password": "password" }'
HTTP/1.1 200 OK
Cache-Control: max-age=0, private, must-revalidate
Content-Type: application/json; charset=utf-8
ETag: W/"d461cee009c4bfaf6577daf7d2fe4c94"
Transfer-Encoding: chunked
Vary: Origin
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Request-Id: 79f9d6d0-055e-4ab9-963f-e8ccc99cd4c3
X-Runtime: 0.212154
X-XSS-Protection: 1; mode=block

{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMzQsInJvbGVzIjpbXSwiZXhwIjoxNDk4MTAzOTM3fQ.pEbPbTzUR2nOlICIfTgFpl5YNNCf59bp43lpSqBL-vk",
    "user": {
        "email": "test@example.com",
        "first_name": null,
        "id": 134,
        "last_name": null,
        "mentor": false,
        "slack_name": null,
        "zip": "11772"
    }
}
```

Our JWT is provided at the `token` key (`eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMzQsInJvbGVzIjpbXSwiZXhwIjoxNDk4MTAzOTM3fQ.pEbPbTzUR2nOlICIfTgFpl5YNNCf59bp43lpSqBL-vk`)

If I go decode that at jwt.io I get the following payload data:
```
{
  "user_id": 134,
  "roles": [],
  "exp": 1498103937
}
```

From there it's a simple find based on the `user_id` column in the payload:
```
2.3.3 :001 > User.find(134)
D, [2017-06-20T22:02:57.402051 #88366] DEBUG -- :   User Load (1.7ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 134], ["LIMIT", 1]]
 => #<User id: 134, email: "test@example.com", zip: "11772", latitude: 40.7758652, longitude: -72.9814877, created_at: "2017-06-21 03:46:50", updated_at: "2017-06-21 03:58:57", mentor: false, slack_name: nil, first_name: nil, last_name: nil, timezone: nil, bio: nil>
```

**Comment by hpjaj** [comment]
@rickr - That makes sense.  Thanks for the fantastic explanation!
