### ISSUE TITLE
Make sentry monitoring better

### ISSUE THREAD

**Issue by wimo7083** [OperationCode/operationcode_backend#383]
# Feature
## Why is this feature being added?

Sentry is adding a bunch of value to our monitoring, we wish to increase this value in the future. 
## What should your feature do?

1.  Configure to include correct build environment (staging, prod)
2. Tie the build id of travis, github and sentry so we can relate build issues to sentry issues. 
3. ~Send logs to chatops for repeated messages, but without spamming them.~
4. Identify routes that require elevated monitoring or de-escalated monitoring. (some routes require every error, some require an increased number of errors).

**Comment by kylemh** [comment]
That's not really how Raven works though. It essentially alerts us to when users encounter an error in their browser.

**Comment by wimo7083** [comment]
Some of the errors above are due to unknown coding/ infra issues that were only found when a user did some action, from looking at the docs you can modify the config for raven in all sorts of ways. 

https://docs.sentry.io/clients/ruby/config/

Currently we only have the default config: https://github.com/OperationCode/operationcode_backend/blob/a3027d7c6cce4db51b708c7c148130c663456a9f/config/environments/production.rb#L95

There are some exceptions we don't currently log, but an example that could be helpful would be to capture specific routes we are concerned with and pipe them to slack: https://docs.sentry.io/clients/ruby/usage/#reporting-messages

**Comment by kylemh** [comment]
Right. I'm saying that Raven is client-side only. There's no server-side implementation of Sentry that I'm aware of.

**Comment by kylemh** [comment]
After chatting a bit more, this does seem like an issue. Clearly some services are reporting via Raven. Perhaps it's an aspect of an e2e implementation w/ Raven.

All aside, most of Raven's errors in #chatops seem very cryptic and unhelpful.

**Comment by wimo7083** [comment]
This has been corrected. 
Will close the ticket once we document the fix and corrective actions _somewhere_ and what we expect sentry to do.

**Comment by wimo7083** [comment]
After playing with sentry here's what I think.
1. Connect sentry and github so that any errors will have the commits tied to them
2. Tie the build id of sentry, travis and github, and the server again so we can have the correct release ID

**Comment by wimo7083** [comment]
Okay so sentry is actually working well. I think now with the addition of staging, we need to prioritize targetting environment. Currently the `api.staging....` is showing up on sentry as production.
