### ISSUE TITLE
Raise an error if jwt secret is unavailable

### ISSUE THREAD

**Issue by rickr** [OperationCode/operationcode_backend#39]
# Feature
## Why is this feature being added?

https://github.com/OperationCode/operationcode_backend/blob/master/app/lib/json_web_token.rb#L8
In order to make debugging easier if the secrets available in the above file are not available we should raise an error with a good error message

## What should your feature do?
Check for the jwt_secret token and raise an error if it doesn't exist.

**Comment by hpjaj** [comment]
@rickr - I can take this one.
