### ISSUE TITLE
Bug: Api::V1::CodeSchoolsController#index is slow

### ISSUE THREAD

**Issue by wimo7083** [OperationCode/operationcode_backend#395]
# Bug Report
## What is the current behavior?
![image](https://user-images.githubusercontent.com/10781353/45436900-108c7400-b671-11e8-859f-7121d938fbc3.png)

https://oss.skylight.io/app/applications/0iQU6bEW8ha1/recent/6h/endpoints

This route is is not our slowest route, but the slower routes are lower impact. This route is used often and appears to be related to repeated sql queries of the form:

`SELECT "locations".* FROM "locations" WHERE "locations"."code_school_id" = ? ORDER BY "locations"."state" ASC, "locations"."city" ASC`

The question mark is skylight notation for repeated queries like this:
```
SELECT "locations".* FROM "locations" WHERE "locations"."code_school_id" = 1 ORDER BY "locations"."state" ASC, "locations"."city" ASC
SELECT "locations".* FROM "locations" WHERE "locations"."code_school_id" = 2 ORDER BY "locations"."state" ASC, "locations"."city" ASC
SELECT "locations".* FROM "locations" WHERE "locations"."code_school_id" = 3 ORDER BY "locations"."state" ASC, "locations"."city" ASC
```

## What is the expected behavior?
This is our busiest route, and the data never changes. I'd expect a much faster response time.

**Comment by wimo7083** [comment]
This is partially addressed in this PR: https://github.com/OperationCode/operationcode_backend/pull/396 by turning the N+1 query into a single query.

@robbkidd is currently working on a way to make serialization faster.

**Comment by robbkidd** [comment]
Any recent data from production on how long this backend API endpoint is taking with the database query portion optimized?

**Comment by wimo7083** [comment]
It's looking much better:
![image](https://user-images.githubusercontent.com/10781353/45847001-b16cd600-bce6-11e8-99f4-297ef28ad2e5.png)

https://oss.skylight.io/app/applications/0iQU6bEW8ha1/recent/6h/endpoints/Api::V1::CodeSchoolsController%23index?responseType=text

Skylight doesn't keep results for too long so sometimes routes don't show up. These are the current slow routes:
![image](https://user-images.githubusercontent.com/10781353/45847043-d6f9df80-bce6-11e8-912f-edfec15053d9.png)

**Comment by wimo7083** [comment]
Changing title and purpose.

**Comment by diegotoral** [comment]
Is there anything left in this issue? Maybe I can help.

**Comment by wimo7083** [comment]
I left this open but forgot to update the information.

This chart: 
https://user-images.githubusercontent.com/10781353/45847001-b16cd600-bce6-11e8-99f4-297ef28ad2e5.png

That while we are a little bit faster, we are using most of our time serializing the query results. If you'd like to work on faster serializing you're more than welcome to.

**Comment by diegotoral** [comment]
Awesome! I will certainly give it a try. Thanks!

I'll dive into the code a little and try to figure out solutions.

**Comment by diegotoral** [comment]
I have a few ideas on how make serialization a bit faster:

1. move to a faster json parser/serializer like `oj`; or
2. migrate from active model serializers to the fatest Netflix fast_jsonapi 

What you think? Any better idea?

**Comment by BRIMIL01** [comment]
Maybe try both and benchmark them to see if one solution is better than the other?

**Comment by wimo7083** [comment]
Here's two more options:
3. Cache results
4. Do 1 or 2 and cache results. 

Code schools only change 1-2 times a month, but we want to do things right before we use tricks.

**Comment by robbkidd** [comment]
There are only two hard things in Computer Science: cache invalidation, naming things, and off-by-one errors.

**Comment by kylemh** [comment]
@wimo7083 what was the resolution here?

**Comment by wimo7083** [comment]
The initial issue was to speed up the query which we did. I'm closing this until we decide it's not fast enough and warrant further work.
