### ISSUE TITLE
Pull all meetups from the meetup API

### ISSUE THREAD

**Issue by rickr** [OperationCode/operationcode_backend#40]
# Feature
## Why is this feature being added?

1. Get all Operation Code meetup data from Meetup.com's API. 
2. Filter the data and save to the database as events.  Event data will be set up in such a way to expand to other platforms (facebook)
   - Write migration to add source_id, source_updated, and group to existing Events table
   - Compare to existing data to ensure events aren't duplicated. 
   - Compare updated_at (available via Meetup's API) to see if an event has been updated. 
3. Write a rake task to pull the data. 
4. Render data as json at events endpoint. 

## What should your feature do?

**Comment by leenyburger** [comment]
Structure for expansion to include other apis: 
@events_meetupdata = data from meet up_api
@events_facebookdata = data from Facebook_api 
@events_all = combines the two variables above and output in JSON format for front end to display.
