### ISSUE TITLE
Document the overall application structure

### ISSUE THREAD

**Issue by wimo7083** [OperationCode/operationcode_backend#411]
# Feature
## Why is this feature being added?
When working on the application the structure and flow is super important to know. We want to be able to easily read the code and using documentation understand what the major areas are.

## What should your feature do?
For this first step, I want to document the various major parts that need to be documented. 

EX:
1. routes.rb
2. models
3. db schema
4.  controllers
5.  configs
6. Anything else

Acceptance criteria:

Include a simple tree diagram of the major parts of the application and include it in the `/docs` folder.

**Comment by wimo7083** [comment]
Assigning myself as placholder, thanks @donquxiote.

**Comment by donquxiote** [comment]
Wanted to check in and make sure I'm on the right track for what y'all are looking for. This is a basic diagram of the models I generated with rails-erd. There's a few options to play around with so it can be a lot cleaner. If y'all want I can include that gem in my pr so y'all can generate these easily in the future too.

[file_name.pdf](https://github.com/OperationCode/operationcode_backend/files/2453093/file_name.pdf)

Next I'll work on diagrams for the other parts listed in the issue.

**Comment by wimo7083** [comment]
This is really awesome and going to be helpful.

Would you mind going over how you created this to see if we can create a rake task to auto generate (and keep this up to date)?


I think keeping track of the data model is very helpful.

I would also like to incorporate more ruby/ rails specific knowledge into documentation so that someone new to the rails framework would understand things such as:

1.  why we have tests here
2. how the test folder mirrors real folder. 
3. How models connects to controllers
4. How the controller folder structure relates to the api url
5. If someone wants to make a change to a scheduled job what they should do.

I'm not asking you to do all this, but as this repo is intended to be a strong learning experience for vets I have two goals.
1. Make the structure of application newbie friendly
2. Document in ways that are not fragile to application changes.

**Comment by wimo7083** [comment]
Gonna mark this as closed for now as we got a schema. And trying to prioritize things.
