### ISSUE TITLE
Allow results to be filtered by location

### ISSUE THREAD

**Issue by rickr** [OperationCode/operationcode_backend#43]
# Feature

**Comment by sabrown84** [comment]
I'd like to try this one. Are there any information or instructions? @rickr

**Comment by sabrown84** [comment]
Any direction on this on @rickr

**Comment by hollomancer** [comment]
Ah, I think this is dependent on the events endpoint being finished.

**Comment by leenyburger** [comment]
@sabrown84 I'm working on the events endpoint. The UI goal is to show events local to the user first, but right now I am just providing the events as json from our API. I am saving the events to the database, so you should be able to access whatever you need. There was some chatter about this being done on the front end. I don't know if anyone has jumped on this on the frontend yet, probably waiting for me! 
I can get a WIP pull request hopefully this week so you can see the data format.

**Comment by hollomancer** [comment]
We can reopen this when we revisit events.
