### ISSUE TITLE
submit button not working

### ISSUE THREAD

**Issue by wegmand** [OperationCode/operationcode_backend#442]
# Feature
## What should your feature do?

---

# Bug Report
## What is the current behavior?
The submit button doesn't work so I can't submit my application

## What is the expected behavior?
To be able to click submit and have my data submitted

## What steps did you take to get this behavior?
Filled out the input boxes and clicked submit

**Comment by wegmand** [comment]
There is only one button on the page I believe. Once you fill out all the
input boxes there’s a button you click to submit your info.

**Comment by wimo7083** [comment]
Sorry I still don't know what page you are talking about. codeschools, some other form, registration for site, mailing list subscribe?

**Comment by wegmand** [comment]
Here is the link to the page:
http://operationcode-pyback.us-east-1.elasticbeanstalk.com/new_school.
There's only one button on the whole page called Submit Request

**Comment by wimo7083** [comment]
Appreciate the clarification. I wasn't sure which web page out of all our web pages, either from the main website, or the different forms we provide users, specifying the specific link was helpful.

**Comment by wimo7083** [comment]
@AllenAnthes is almost done with fixing this.

**Comment by wimo7083** [comment]
@wegmand 

Hi there, this working now. Thank you for being patient.

**Comment by wegmand** [comment]
Thanks!
