### ISSUE TITLE
Change autojoin channel to #career-advice

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/operationcode_backend#462]
# Feature
## Why is this feature being added?
Current autojoin channel is set to #random and not #career-advice, per #447. 

## What should your feature do?
Change Slack auto-join channel to C1T66M57G. This ticket can be closed without action if custom channel invites are merged first.

**Comment by wimo7083** [comment]
This should be a quick win for someone's first PR. This is the file you'd need to change: 
https://github.com/OperationCode/operationcode_backend/blob/master/app/jobs/slack_jobs/inviter_job.rb

**Comment by markchernov** [comment]
Can I try this one?

**Comment by dmarchante** [comment]
all yours @markchernov

**Comment by kylemh** [comment]
Closed in #463
