### ISSUE TITLE
Fix "validation_regex" issue in app/models/user.rb

### ISSUE THREAD

**Issue by rickr** [OperationCode/operationcode_backend#47]
Insufficient validation for 'email' using /@/. Use \A and \z as anchors

https://codeclimate.com/github/OperationCode/operationcode_backend/app/models/user.rb#issue_59429d1c957fc9000100005f

**Comment by cameronhopkin** [comment]
/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

**Comment by rickr** [comment]
We could probably go even simpler: 
`\A.*@.*\z`
