### ISSUE TITLE
Fix "Rubocop/Lint/UselessAssignment" issue in app/controllers/api/v1/sessions_controller.rb

### ISSUE THREAD

**Issue by rickr** [OperationCode/operationcode_backend#48]
Useless assignment to variable - `user`.

https://codeclimate.com/github/OperationCode/operationcode_backend/app/controllers/api/v1/sessions_controller.rb#issue_59429d20957fc90001000068

**Comment by hpjaj** [comment]
@rickr - I can take this one.
