### ISSUE TITLE
Ruby 2.3 is unsupported

### ISSUE THREAD

**Issue by ohaiwalt** [OperationCode/operationcode_backend#487]
@wimo7083 and I discovered last night that the backend is running on Debian Jessie, and while attempting to upgrade to a more recent version for OS support, we found that the backend Docker base image is Ruby:2.3.3. Ruby 2.3 is now [unsupported](https://www.ruby-lang.org/en/news/2019/03/31/support-of-ruby-2-3-has-ended/) as of March 31st, 2019. From that link:

> We highly recommend that you upgrade to Ruby 2.6 or 2.5 as soon as possible.

There's a variety of upgrades that need to happen here to bring us to more current (and supported) toolchain versions.

* Ruby version >=2.5
* Rails version to whatever supports Ruby >=2.5
* Debian Jessie -> Debian Stretch or better

I opened #484 to see if tests would pass, but they did not. If anyone wants to investigate upgrading Ruby and Rails, I am happy to assist with troubleshooting in that effort.

**Comment by jaydorsey** [comment]
I'm taking a stab at this now. I'll have a few PR's open shortly related to this

**Comment by kylemh** [comment]
Closed in #500
