### ISSUE TITLE
Change from Factory Girl to fixtures

### ISSUE THREAD

**Issue by rickr** [OperationCode/operationcode_backend#58]
# Feature
## Why is this feature being added?

Factory girl is very slow. While we don't have too many features I'd like to switch over to fixtures

## What should your feature do?
Replace all factories with features, make all tests pass.

**Comment by ianroberts131** [comment]
If nobody else is looking at this, I'll start digging in to see the best way to make this conversion happen.

**Comment by kylemh** [comment]
@ianroberts131 all yours!

**Comment by hpjaj** [comment]
@hollomancer - FactoryGirl is much more beginner friendly, more flexible, and much more well known to Rails developers. 

Our test suite runs plenty fast.  Fixtures would not give us any significant improvements in speed.  Especially when you weigh all the constraints it puts in place, when compared to the flexible nature of FactoryGirl.

We have quite a few tests depending heavily on FactoryGirl today. I recommend that we stay with FactoryGirl, and remove this issue.

**Comment by hollomancer** [comment]
@hpjaj, concur. I do not think that test speed is a significant limitation to our development on the backend right now - we can reopen if it is.
