### ISSUE TITLE
Run migrations on container start

### ISSUE THREAD

**Issue by rickr** [OperationCode/operationcode_backend#61]
# Feature
## Why is this feature being added?

Migrations currently have to be run manually once they hit production.

## What should your feature do?
Create a script that will do any startup related tasks (eg rails db:migrate).
It should end with `bundle exec puma -C config/puma.rb`

**Comment by kirbygit** [comment]
Is this related to heroku threads? or Procfile if thats the case I can have this issue. Let me know if this is the Procfile and puma.rb

**Comment by rickr** [comment]
No - this will be a little shell script that's run as Docker's start script.

**Comment by kirbygit** [comment]
ok

**Comment by PSkaggs** [comment]
I can do this.

**Comment by hpjaj** [comment]
@PSkaggs - Are you still interested in taking this on?  If yes, its yours!  Just let us know so we can mark it as **in progress**.

**Comment by PSkaggs** [comment]
Sure, I'll take it.

**Comment by hpjaj** [comment]
@PSkaggs - it is yours!

**Comment by PSkaggs** [comment]
@hpjaj I'm not sure what all you wanted with this feature.  I currently have a script that runs migrations when starting the container.  Did you want the database seeded as well?

**Comment by hpjaj** [comment]
@PSkaggs - No, no seeding.  Just want to make sure that the migrations are ran when the container starts.

**Comment by PSkaggs** [comment]
I suppose I'm a little confused as to how you are running this in production.  If you are using `yarn` then there is already a `make db_migrate` in the script.  Unless you are just using `make` or `docker-compose up --build` or something similar?  Anyway, I've got a PR for you that does what you want.

**Comment by kylemh** [comment]
@ohaiwalt does this maybe explain our server outage per build?

**Comment by ohaiwalt** [comment]
@kylemh negative, unrelated.

**Comment by hpjaj** [comment]
Completed:  https://github.com/OperationCode/operationcode_backend/pull/186
