### ISSUE TITLE
Convert current code_schools endpoint generation to a more extendible architecture

### ISSUE THREAD

**Issue by kylemh** [OperationCode/operationcode_backend#76]
# Improvement
## Why is this improvement being suggested?
I noticed that Galvanize is missing some locations, there may be other code schools with new locations or other out-of-date details. There also have been a few code school representatives that want to add their school to our site, but have to deal with manually updating `code_schools.yaml`. Let's implement CRUD functionality by offering an interface for code school reps and OC admins to add/edit/delete code school data.

## What would your improvement do?
Automates/improves the current functionality of adding/updating/deleting code schools from our API.

### NOTE: Information detailed by @hpjaj [here](https://github.com/OperationCode/operationcode_backend/issues/36#issuecomment-312957658)!

- create a new `CodeSchool` db table
- [CRUD](https://en.wikipedia.org/wiki/Create,_read,_update_and_delete) API endpoints for `CodeSchool` records 
- `rake` task that creates a `CodeSchool` record for each entry in `code_schools.yml` 
- wire up the existing `:index` endpoint to fetch `CodeSchool` db records
- test coverage for new endpoints
- update our [API documentation](https://github.com/OperationCode/operationcode_backend/blob/master/apiary.apib)

**Comment by kylemh** [comment]
If this issue is completed before #24 - close that issue.

**Comment by PrimeTimeTran** [comment]
@kylemh I'll try this one if you don't mind me taking it on.

**Comment by hpjaj** [comment]
@PrimeTimeTran - You can ping me if you have any questions on it!

**Comment by hpjaj** [comment]
@PrimeTimeTran - You are welcome to take this one on.  If you choose to do so, be sure to: 

1. set yourself as the **assignee**
2. change the label status from **available** to **in progress**

If for some reason you run into issues making these updates, ping me or @kylemh and we'll update them for you.

**Comment by PrimeTimeTran** [comment]
@hpjaj would you mind giving me a review of what I've got so far? I don't want to make a PR until I have all the tests written as well.
https://github.com/PrimeTimeTran/operationcode_backend

**Comment by hpjaj** [comment]
@PrimeTimeTran - Can you create a pull request in your repository, so that all of your changes are isolated to a branch for code review?  

If you have never created a pull request for an open source project before, this link can give you some guidance on how to do so:  https://mind-on-rails.herokuapp.com/notes/313-free-course-on-how-to-contribute-to-an-open-source-project

**Comment by hpjaj** [comment]
Completed here: https://github.com/OperationCode/operationcode_backend/pull/164
