### ISSUE TITLE
POST request on join page

### ISSUE THREAD

**Issue by codedoll** [OperationCode/operationcode_backend#77]
# Bug Report
## What is the current behavior?
After completing the sign-up form on https://www.operationcode.org/join, the POST request does not go through. 
## What is the expected behavior?
The page should redirect to a different page and the user should receive a welcome email.
### Screenshots
<img width="932" alt="screen shot 2017-07-08 at 1 42 04 pm" src="https://user-images.githubusercontent.com/17578236/27987920-22d4ce5e-63e4-11e7-9afb-540544a37d13.png">
<img width="933" alt="screen shot 2017-07-08 at 1 44 04 pm" src="https://user-images.githubusercontent.com/17578236/27987922-22d5cebc-63e4-11e7-84c4-3d445be67f54.png">
<img width="935" alt="screen shot 2017-07-08 at 1 44 11 pm" src="https://user-images.githubusercontent.com/17578236/27987921-22d5b418-63e4-11e7-8c21-cab85a8036f7.png">

**Comment by sethbergman** [comment]
Are you doing doing any CORS? Also, content type should be application/json for the request.

**Comment by rickr** [comment]
This was a bug on the frontend and was fixed in operationcode/operationcode_frontend#228
