### ISSUE TITLE
Ability to pull membership numbers by zip & total

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/operationcode_backend#78]
# Feature
## Why is this feature being added?
I'd like to be able to query our database to know exactly how many users we have, and what locations we have the most members in. This also enables us to do some interesting visualizations in the frontend.

The intent here is to be able to query from the frontend, or even from Slack, how many folks we have from a given state or region.
## What should your feature do?
* Query user database for number of users total.
* Query user database for number of users by zipcode.

**Comment by hpjaj** [comment]
@rickr - I can take this one.

**Comment by rickr** [comment]
https://github.com/alexreisner/geocoder#for-activerecord-models should get you pointed in the right direction.
