### ISSUE TITLE
API endpoint for aggregated open source contribution statistics

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/operationcode_backend#79]
# Feature
## Why is this feature being added?
We need to better demonstrate the impact that our organization has on the open source community. I would like to see a page showing our members on Github, what they have created, and how the Operation Code organization has enabled that.
## What should your feature do?
MVP: Use Github's API to retrieve statistics on contributions to /OperationCode/foo repositories, and consolidate into a single database.

Corresponding issue for data visualization in the frontend repository - https://github.com/OperationCode/operationcode_frontend/issues/231

**Comment by hollomancer** [comment]
I believe hood.ie may have already done some interesting work on this that we can purpose.

**Comment by hpjaj** [comment]
@hollomancer @rickr - Here are the results of some brainstorming on types of stats that one might want.  We would not be doing all of these, of course, but can you take a look and narrow down what **specifically** you are looking for in this issue?

#### Contributions to OC 

- Per repo
  - Across all users
    - Number of pull requests
    - Number of commits
      - Number of commits on a given day
    - Rate/frequency of commits per unit time
    - Number us users that have made a commit 
      - Unique 
    - Number of users that have closed a PR
      - Unique 
    - Average number of commits per user 
    - Average number of closed PR's per user 
    - Average number of lines of code added per user 
    - Average number of lines of code removed per user
        
  - Per user
    - Number of commits
    - Lines of code added
    - Lines of code removed
    - Number of pull requests
    - Number of assigned issues
- Across all repos
  - Across all users ?        
  - Per user ?

**Comment by hollomancer** [comment]
This is all good stuff - we should get a sense of what's easiest to derive quickly as an MVP.

**Comment by hollomancer** [comment]
MVP:

Across all repos, and all users
* Number of pull requests
* Number of commits
* Number of commits on a given day
* Number of unique users that have made a commit
* Number of users that have closed a PR
* Average number of commits per user
* Average number of closed PR's per user
