### ISSUE TITLE
Create resource endpoint

### ISSUE THREAD

**Issue by rickr** [OperationCode/operationcode_backend#8]
This is a:

- [x] Feature request
- [ ] Bug report

# Features
## What is your new feature?
Add a new `resources` endpoint.

## What should your feature do?
This endpoint should
- [ ] be sectioned into areas of interest or languages (eg ruby, frontend, backend, machine learning)
- [ ] have an index listing all available sections
- [ ] be able to return all sections

**Comment by aaron-suarez** [comment]
So let me see if I understand. The operationcode_backend repository is specifically for the api. Right now, it looks like we've got v1 of the api which includes status, users, and code_schools. You can only GET status, POST users, and GET code_schools.

From what I'm understanding, we need a GET resources/index which will return the available sections, then a GET resources/all which will return all the sections, as well as GET resources/:section which will just return the resources for the specified section.

Am I missing anything?

**Comment by rickr** [comment]
I think we would have the following routes:

GET /resources - this either lists all resources or just contains links to all sub sections
GET /resources/:section - this lists all resources for this section, including how to get each one
GET /resources/:section/:id - A specific resource

**Comment by krzemienski** [comment]
Something to note a resource can be up voted. It might help to look at the design of the app I am doing that will be calling this endpoint in order for the model to be in order. @aaron-suarez see the designs here:

https://drive.google.com/drive/folders/0B9jlP4wy3NmhNHlJM1F5VzlLekE?usp=sharing 

Specifically the screen dealing resources is **Learn.png**

**Comment by krzemienski** [comment]
Also in the future we will open the access for anyone to submit a resource so there needs to an endpoint for
 
POST /resources/submit

which means we need to have a

**submitted_by=user_id**

in the model.

**Comment by aaron-suarez** [comment]
Ok so these are the routes then 

GET /resources - this either lists all resources or just contains links to all sub sections
GET /resources/:section - this lists all resources for this section, including how to get each one
GET /resources/:section/:id - A specific resource
POST /resources/submit - Add a new resource to the data collection
POST /resources/vote/:section/:id - Up Vote a resource

Will we need another route to remove your vote if you mistakenly upvoted a resource you don't actually like? 

And we definitely need to check to ensure that the person is logged in and hasn't already upvoted a resource. We don't want any bots or trolls artificially inflating the vote count for a particular resource. Will that control need to be included in the route itself, or just in the method that checks it?

**Comment by rickr** [comment]
To keep track of votes resources will need to be stored in the DB.

The model should be called 'Resource'.

It should have the following columns:

`upvotes` - `int`
`url` - `string`
`description` - `text`
`title` - `string`
The standard rails `created_at` and `updated_at`
Whatever other fields you think are needed to display the material you currently have.

Instead of sections we can move to tags. The `Resource` model will have a `has_and_belongs_to_many` `tags`

The `tags` table should be called `resources_tags` and have the following columns:
`resource_id` - `int`
`tag_id` - `int`.

(This is a standard HABTM table - please feel free to double check me in the rails docs).

AuthN/AuthZ can be checked via devise once #12 is closed.

The `ResourcesController` should have the following end points:

`GET /resources` - This will return an array of all resources. It should take the following query params:
`tags` - CSV separated list of tags. If this param is present only resources with the given tags should be returned

**Comment by hpjaj** [comment]
@rickr @alexspence @kylemh - I can take this one

**Comment by aaron-suarez** [comment]
@hpjaj I'm fine with that.. I wish I had more time to devote to working these open source projects. Anyway, feel free to use my code in the PR as a starting point

**Comment by hpjaj** [comment]
@aaron-suarez - Ah, apologies, I did not realize you had already started a PR for this.  I'm happy to find another issue if you'd like to continue on with this one?

**Comment by aaron-suarez** [comment]
@hpjaj I'd like it to get done, and I don't see myself honestly doing it in a reasonable time frame. I mean, look at the dates, it's been two months since I've worked on it.

[Here's the link](https://github.com/aaron-suarez/operationcode_backend/tree/create-resources-endpoint) to my branch for it. I'm not sure at the moment if there's any uncommitted changes I have locally. If there is, I'll commit it today.

**Comment by hpjaj** [comment]
@aaron-suarez - Sounds good!

**Comment by hpjaj** [comment]
@rickr @hollomancer @alexspence @jjhampton @kylemh - Do we want backend restrictions preventing a user from up voting a resource more than one time, as @aaron-suarez described here: 

> And we definitely need to check to ensure that the person is logged in and hasn't already upvoted a resource. We don't want any bots or trolls artificially inflating the vote count for a particular resource.
