### ISSUE TITLE
Create job to merge Meetup user data into Postgres

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/operationcode_backend#87]
# Feature
## Why is this feature being added?
@rickr, we have a lot of data in Meetup that should be synced up with our regular user database, regarding members that go to our regular meetups, chapters and rate of growth, etc.

## What should your feature do?

**Comment by hpjaj** [comment]
@hollomancer - I don't believe we are going to be able to satisfy this issue.  Reason being, the only way I can think that we can link a Meetup attendee back to an OC `User` is through their email address (unless there are other ways?).

And the [Meetup API](https://www.meetup.com/meetup_api/) does not yield a member's email address.  Here is [a sample](https://gist.github.com/hpjaj/b52db3c6bb1beef2bd8b194677f5d7a1) of the response from their member id endpoint.

Do you have other ideas on how to link a Meetup attendee back to an OC `User`?  If not, perhaps we should close this issue?

**Comment by hollomancer** [comment]
@hpjaj, you are correct and I've spoken to Meetup about this problem. It is on their roadmap to allow additional information allowing for this sort of linking, but until that happens, this can be closed.

**Comment by hollomancer** [comment]
Meetup has added this functionality! cc @hpjaj 

https://www.meetup.com/meetup_api/docs/pro/:urlname/members/

**Comment by BRIMIL01** [comment]
I can grab this issue. I assume this would only augment existing data and not overwrite anything correct? I also assume https://github.com/OperationCode/operationcode_backend/issues/163 would be ideal to have done prior to this so the job can get scheduled.

**Comment by wimo7083** [comment]
You can work on this issue without 163. We are discussing whether to use sidkiq_cron or sidekiq_** and I think that if you go about this using a Sidekiq::Worker class similar to PR #410  you won't have to worry about the random issues that PR has. 

Which would you rather work on first?

**Comment by BRIMIL01** [comment]
I'll do this one first and implement it as a sidekiq worker since that seems to be aligned with the future state of scheduled jobs.

**Comment by wimo7083** [comment]
Awesome thank you! I'll assign myself as a placeholder.
