### ISSUE TITLE
Create user profile models and attributes

### ISSUE THREAD

**Issue by rickr** [OperationCode/operationcode_backend#88]
# Feature
## Why is this feature being added?

See operationcode/operationcode_frontend#265 for background.

## What should your feature do?
Add the models/columns listed in the following document:
https://docs.google.com/document/d/1NET6RmBiCgc2IUJvjYRzdykjcwAMG-859ShsOhMmVqU/edit#

**Comment by hpjaj** [comment]
@davidmolina @rickr @hollomancer - Can you answer the questions, and provide feedback, on my interpretation of this feature's goals.  It covers what models and attributes are being created:

https://hackmd.io/EYVhGMGYDYE5ILSQCzMcgJpADAghpCLgOwE7YBM4AHNRbEA=?both

It is essentially a checklist of acceptance criteria.  Feel free to make edits in the file itself.

**Comment by hollomancer** [comment]
@hpjaj, added a couple fields.

**Comment by hpjaj** [comment]
@hollomancer - are you able to answer any of the questions, or shall we leave those for @rickr @davidmolina

**Comment by hollomancer** [comment]
Added some comments, @rickr will need to weigh in on the rest.

**Comment by hollomancer** [comment]
@rickr, I'm wondering if we might need some intermediate states here;
- Slack users who we have web signup information for
- Users who never logged into Slack
- Meetup members (we have another 2k entries there that need to be reconciled)

**Comment by rickr** [comment]
With the advent of [this doc](https://github.com/OperationCode/documents/pull/6/files) lets reduce the scope of this to just attributes on the user model. I'd like to do some work to map out what's outlined in the doc to the correct models.

**Comment by hpjaj** [comment]
@rickr @hollomancer - is this all for now:

```ruby
class AddMoreAttributesToUser < ActiveRecord::Migration[5.0]
  def change
    add_column :users, :address_1, :string
    add_column :users, :address_2, :string
    add_column :users, :city, :string
    add_column :users, :username, :string
    add_column :users, :volunteer, :boolean, default: false
    add_column :users, :branch_of_service, :string
    add_column :users, :years_of_service, :float
    add_column :users, :pay_grade, :string
    add_column :users, :military_occupational_specialty, :string
    add_column :users, :github, :string
    add_column :users, :twitter, :string
    add_column :users, :linkedin, :string
    add_column :users, :employment_status, :string
    add_column :users, :education, :string
  end
end
```

**Comment by rickr** [comment]
That's a good start for now I think. 

Some of these might need to be broken out into additional models (we might want to list multiple education sources for example) but I think we can migrate when we need to.
