### ISSUE TITLE
Document Code Schools endpoint

### ISSUE THREAD

**Issue by rickr** [OperationCode/operationcode_backend#9]
This is a:

- [x] Feature request
- [ ] Bug report

# Features
## What is your new feature?

Document the code schools endpoint.

## What should your feature do?

Document path, format, and options.

**Comment by alexspence** [comment]
What do we think about hosting a Swagger UI for the opcode API?

**Comment by hollomancer** [comment]
I like the idea of using Swagger, or maybe Apiary.

**Comment by hollomancer** [comment]
We have Apiary accounts available for those willing to document.

**Comment by PrimeTimeTran** [comment]
@hollomancer I think I finished this with this PR:
https://github.com/OperationCode/operationcode_backend/pull/164

If I'm correct does that mean this issue should be closed?

**Comment by hpjaj** [comment]
This was completed in https://github.com/OperationCode/operationcode_backend/pull/164
