### ISSUE TITLE
Add Coder Camps to site

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/operationcode_backend#93]
https://www.codercamps.com/

**Comment by kylemh** [comment]
This issue has been marked "beginner friendly"!

To accomplish this task, just follow this simple process (assuming you have git installed):

1. [Fork this repository](https://help.github.com/articles/fork-a-repo/)

2. [Clone your forked copy of the repository](https://help.github.com/articles/cloning-a-repository/)

3. Open the project on your machine, and go to `config/code_schools.yaml` [(here)](https://help.github.com/articles/cloning-a-repository/).

4. Make the edits on any text editor while following the format described in it's comments.

5. Run the following commands on your terminal, in order:
```bash
git add .
git commit -m "Resolve #93"
git push
```

6. Once you've pushed the changes to your forked copy, go [here](https://github.com/OperationCode/operationcode_backend/pulls) and [open a new pull request](https://help.github.com/articles/creating-a-pull-request/)!
