### ISSUE TITLE
Remove RefactorU from code_schools.yaml

### ISSUE THREAD

**Issue by kylemh** [OperationCode/operationcode_backend#99]
# Feature
## Why is this feature being added?
According to [this](https://www.coursereport.com/reports/2017-coding-bootcamp-market-size-research), RefactorU has shut down.

## What should your feature do?
Remove RefactorU from the code_schools.yaml file so our API does not serve it up to be rendered as a potential code school for veterans to use.

**Comment by rickr** [comment]
I'd like to see at least one more source before we accomplish this.
